/**
 * This class is generated by jOOQ
 */
package com.example.mindoc_transfer.db.pojo.tables.daos;


import com.example.mindoc_transfer.db.pojo.tables.MdAttachment;
import com.example.mindoc_transfer.db.pojo.tables.records.MdAttachmentRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MdAttachmentDao extends DAOImpl<MdAttachmentRecord, com.example.mindoc_transfer.db.pojo.tables.pojos.MdAttachment, Integer> {

    /**
     * Create a new MdAttachmentDao without any configuration
     */
    public MdAttachmentDao() {
        super(MdAttachment.MD_ATTACHMENT, com.example.mindoc_transfer.db.pojo.tables.pojos.MdAttachment.class);
    }

    /**
     * Create a new MdAttachmentDao with an attached configuration
     */
    public MdAttachmentDao(Configuration configuration) {
        super(MdAttachment.MD_ATTACHMENT, com.example.mindoc_transfer.db.pojo.tables.pojos.MdAttachment.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.example.mindoc_transfer.db.pojo.tables.pojos.MdAttachment object) {
        return object.getAttachmentId();
    }

    /**
     * Fetch records that have <code>attachment_id IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdAttachment> fetchByAttachmentId(Integer... values) {
        return fetch(MdAttachment.MD_ATTACHMENT.ATTACHMENT_ID, values);
    }

    /**
     * Fetch a unique record that has <code>attachment_id = value</code>
     */
    public com.example.mindoc_transfer.db.pojo.tables.pojos.MdAttachment fetchOneByAttachmentId(Integer value) {
        return fetchOne(MdAttachment.MD_ATTACHMENT.ATTACHMENT_ID, value);
    }

    /**
     * Fetch records that have <code>book_id IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdAttachment> fetchByBookId(Integer... values) {
        return fetch(MdAttachment.MD_ATTACHMENT.BOOK_ID, values);
    }

    /**
     * Fetch records that have <code>document_id IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdAttachment> fetchByDocumentId(Integer... values) {
        return fetch(MdAttachment.MD_ATTACHMENT.DOCUMENT_ID, values);
    }

    /**
     * Fetch records that have <code>file_name IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdAttachment> fetchByFileName(String... values) {
        return fetch(MdAttachment.MD_ATTACHMENT.FILE_NAME, values);
    }

    /**
     * Fetch records that have <code>file_path IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdAttachment> fetchByFilePath(String... values) {
        return fetch(MdAttachment.MD_ATTACHMENT.FILE_PATH, values);
    }

    /**
     * Fetch records that have <code>file_size IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdAttachment> fetchByFileSize(Double... values) {
        return fetch(MdAttachment.MD_ATTACHMENT.FILE_SIZE, values);
    }

    /**
     * Fetch records that have <code>http_path IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdAttachment> fetchByHttpPath(String... values) {
        return fetch(MdAttachment.MD_ATTACHMENT.HTTP_PATH, values);
    }

    /**
     * Fetch records that have <code>file_ext IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdAttachment> fetchByFileExt(String... values) {
        return fetch(MdAttachment.MD_ATTACHMENT.FILE_EXT, values);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdAttachment> fetchByCreateTime(Timestamp... values) {
        return fetch(MdAttachment.MD_ATTACHMENT.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>create_at IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdAttachment> fetchByCreateAt(Integer... values) {
        return fetch(MdAttachment.MD_ATTACHMENT.CREATE_AT, values);
    }
}
