/**
 * This class is generated by jOOQ
 */
package com.example.mindoc_transfer.db.pojo.tables.daos;


import com.example.mindoc_transfer.db.pojo.tables.MdBooks;
import com.example.mindoc_transfer.db.pojo.tables.records.MdBooksRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MdBooksDao extends DAOImpl<MdBooksRecord, com.example.mindoc_transfer.db.pojo.tables.pojos.MdBooks, Integer> {

    /**
     * Create a new MdBooksDao without any configuration
     */
    public MdBooksDao() {
        super(MdBooks.MD_BOOKS, com.example.mindoc_transfer.db.pojo.tables.pojos.MdBooks.class);
    }

    /**
     * Create a new MdBooksDao with an attached configuration
     */
    public MdBooksDao(Configuration configuration) {
        super(MdBooks.MD_BOOKS, com.example.mindoc_transfer.db.pojo.tables.pojos.MdBooks.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.example.mindoc_transfer.db.pojo.tables.pojos.MdBooks object) {
        return object.getBookId();
    }

    /**
     * Fetch records that have <code>book_id IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdBooks> fetchByBookId(Integer... values) {
        return fetch(MdBooks.MD_BOOKS.BOOK_ID, values);
    }

    /**
     * Fetch a unique record that has <code>book_id = value</code>
     */
    public com.example.mindoc_transfer.db.pojo.tables.pojos.MdBooks fetchOneByBookId(Integer value) {
        return fetchOne(MdBooks.MD_BOOKS.BOOK_ID, value);
    }

    /**
     * Fetch records that have <code>book_name IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdBooks> fetchByBookName(String... values) {
        return fetch(MdBooks.MD_BOOKS.BOOK_NAME, values);
    }

    /**
     * Fetch records that have <code>identify IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdBooks> fetchByIdentify(String... values) {
        return fetch(MdBooks.MD_BOOKS.IDENTIFY, values);
    }

    /**
     * Fetch a unique record that has <code>identify = value</code>
     */
    public com.example.mindoc_transfer.db.pojo.tables.pojos.MdBooks fetchOneByIdentify(String value) {
        return fetchOne(MdBooks.MD_BOOKS.IDENTIFY, value);
    }

    /**
     * Fetch records that have <code>order_index IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdBooks> fetchByOrderIndex(Integer... values) {
        return fetch(MdBooks.MD_BOOKS.ORDER_INDEX, values);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdBooks> fetchByDescription(String... values) {
        return fetch(MdBooks.MD_BOOKS.DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>label IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdBooks> fetchByLabel(String... values) {
        return fetch(MdBooks.MD_BOOKS.LABEL, values);
    }

    /**
     * Fetch records that have <code>privately_owned IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdBooks> fetchByPrivatelyOwned(Integer... values) {
        return fetch(MdBooks.MD_BOOKS.PRIVATELY_OWNED, values);
    }

    /**
     * Fetch records that have <code>private_token IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdBooks> fetchByPrivateToken(String... values) {
        return fetch(MdBooks.MD_BOOKS.PRIVATE_TOKEN, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdBooks> fetchByStatus(Integer... values) {
        return fetch(MdBooks.MD_BOOKS.STATUS, values);
    }

    /**
     * Fetch records that have <code>editor IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdBooks> fetchByEditor(String... values) {
        return fetch(MdBooks.MD_BOOKS.EDITOR, values);
    }

    /**
     * Fetch records that have <code>doc_count IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdBooks> fetchByDocCount(Integer... values) {
        return fetch(MdBooks.MD_BOOKS.DOC_COUNT, values);
    }

    /**
     * Fetch records that have <code>comment_status IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdBooks> fetchByCommentStatus(String... values) {
        return fetch(MdBooks.MD_BOOKS.COMMENT_STATUS, values);
    }

    /**
     * Fetch records that have <code>comment_count IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdBooks> fetchByCommentCount(Integer... values) {
        return fetch(MdBooks.MD_BOOKS.COMMENT_COUNT, values);
    }

    /**
     * Fetch records that have <code>cover IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdBooks> fetchByCover(String... values) {
        return fetch(MdBooks.MD_BOOKS.COVER, values);
    }

    /**
     * Fetch records that have <code>theme IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdBooks> fetchByTheme(String... values) {
        return fetch(MdBooks.MD_BOOKS.THEME, values);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdBooks> fetchByCreateTime(Timestamp... values) {
        return fetch(MdBooks.MD_BOOKS.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>member_id IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdBooks> fetchByMemberId(Integer... values) {
        return fetch(MdBooks.MD_BOOKS.MEMBER_ID, values);
    }

    /**
     * Fetch records that have <code>modify_time IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdBooks> fetchByModifyTime(Timestamp... values) {
        return fetch(MdBooks.MD_BOOKS.MODIFY_TIME, values);
    }

    /**
     * Fetch records that have <code>version IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdBooks> fetchByVersion(Long... values) {
        return fetch(MdBooks.MD_BOOKS.VERSION, values);
    }
}
