/**
 * This class is generated by jOOQ
 */
package com.example.mindoc_transfer.db.pojo.tables.daos;


import com.example.mindoc_transfer.db.pojo.tables.MdDocuments;
import com.example.mindoc_transfer.db.pojo.tables.records.MdDocumentsRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MdDocumentsDao extends DAOImpl<MdDocumentsRecord, com.example.mindoc_transfer.db.pojo.tables.pojos.MdDocuments, Integer> {

    /**
     * Create a new MdDocumentsDao without any configuration
     */
    public MdDocumentsDao() {
        super(MdDocuments.MD_DOCUMENTS, com.example.mindoc_transfer.db.pojo.tables.pojos.MdDocuments.class);
    }

    /**
     * Create a new MdDocumentsDao with an attached configuration
     */
    public MdDocumentsDao(Configuration configuration) {
        super(MdDocuments.MD_DOCUMENTS, com.example.mindoc_transfer.db.pojo.tables.pojos.MdDocuments.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.example.mindoc_transfer.db.pojo.tables.pojos.MdDocuments object) {
        return object.getDocumentId();
    }

    /**
     * Fetch records that have <code>document_id IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdDocuments> fetchByDocumentId(Integer... values) {
        return fetch(MdDocuments.MD_DOCUMENTS.DOCUMENT_ID, values);
    }

    /**
     * Fetch a unique record that has <code>document_id = value</code>
     */
    public com.example.mindoc_transfer.db.pojo.tables.pojos.MdDocuments fetchOneByDocumentId(Integer value) {
        return fetchOne(MdDocuments.MD_DOCUMENTS.DOCUMENT_ID, value);
    }

    /**
     * Fetch records that have <code>document_name IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdDocuments> fetchByDocumentName(String... values) {
        return fetch(MdDocuments.MD_DOCUMENTS.DOCUMENT_NAME, values);
    }

    /**
     * Fetch records that have <code>identify IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdDocuments> fetchByIdentify(String... values) {
        return fetch(MdDocuments.MD_DOCUMENTS.IDENTIFY, values);
    }

    /**
     * Fetch records that have <code>book_id IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdDocuments> fetchByBookId(Integer... values) {
        return fetch(MdDocuments.MD_DOCUMENTS.BOOK_ID, values);
    }

    /**
     * Fetch records that have <code>parent_id IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdDocuments> fetchByParentId(Integer... values) {
        return fetch(MdDocuments.MD_DOCUMENTS.PARENT_ID, values);
    }

    /**
     * Fetch records that have <code>order_sort IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdDocuments> fetchByOrderSort(Integer... values) {
        return fetch(MdDocuments.MD_DOCUMENTS.ORDER_SORT, values);
    }

    /**
     * Fetch records that have <code>markdown IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdDocuments> fetchByMarkdown(String... values) {
        return fetch(MdDocuments.MD_DOCUMENTS.MARKDOWN, values);
    }

    /**
     * Fetch records that have <code>release IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdDocuments> fetchByRelease(String... values) {
        return fetch(MdDocuments.MD_DOCUMENTS.RELEASE, values);
    }

    /**
     * Fetch records that have <code>content IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdDocuments> fetchByContent(String... values) {
        return fetch(MdDocuments.MD_DOCUMENTS.CONTENT, values);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdDocuments> fetchByCreateTime(Timestamp... values) {
        return fetch(MdDocuments.MD_DOCUMENTS.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>member_id IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdDocuments> fetchByMemberId(Integer... values) {
        return fetch(MdDocuments.MD_DOCUMENTS.MEMBER_ID, values);
    }

    /**
     * Fetch records that have <code>modify_time IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdDocuments> fetchByModifyTime(Timestamp... values) {
        return fetch(MdDocuments.MD_DOCUMENTS.MODIFY_TIME, values);
    }

    /**
     * Fetch records that have <code>modify_at IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdDocuments> fetchByModifyAt(Integer... values) {
        return fetch(MdDocuments.MD_DOCUMENTS.MODIFY_AT, values);
    }

    /**
     * Fetch records that have <code>version IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdDocuments> fetchByVersion(Long... values) {
        return fetch(MdDocuments.MD_DOCUMENTS.VERSION, values);
    }
}
