/**
 * This class is generated by jOOQ
 */
package com.example.mindoc_transfer.db.pojo.tables.daos;


import com.example.mindoc_transfer.db.pojo.tables.MdDocumentHistory;
import com.example.mindoc_transfer.db.pojo.tables.records.MdDocumentHistoryRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MdDocumentHistoryDao extends DAOImpl<MdDocumentHistoryRecord, com.example.mindoc_transfer.db.pojo.tables.pojos.MdDocumentHistory, Integer> {

    /**
     * Create a new MdDocumentHistoryDao without any configuration
     */
    public MdDocumentHistoryDao() {
        super(MdDocumentHistory.MD_DOCUMENT_HISTORY, com.example.mindoc_transfer.db.pojo.tables.pojos.MdDocumentHistory.class);
    }

    /**
     * Create a new MdDocumentHistoryDao with an attached configuration
     */
    public MdDocumentHistoryDao(Configuration configuration) {
        super(MdDocumentHistory.MD_DOCUMENT_HISTORY, com.example.mindoc_transfer.db.pojo.tables.pojos.MdDocumentHistory.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.example.mindoc_transfer.db.pojo.tables.pojos.MdDocumentHistory object) {
        return object.getHistoryId();
    }

    /**
     * Fetch records that have <code>history_id IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdDocumentHistory> fetchByHistoryId(Integer... values) {
        return fetch(MdDocumentHistory.MD_DOCUMENT_HISTORY.HISTORY_ID, values);
    }

    /**
     * Fetch a unique record that has <code>history_id = value</code>
     */
    public com.example.mindoc_transfer.db.pojo.tables.pojos.MdDocumentHistory fetchOneByHistoryId(Integer value) {
        return fetchOne(MdDocumentHistory.MD_DOCUMENT_HISTORY.HISTORY_ID, value);
    }

    /**
     * Fetch records that have <code>action IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdDocumentHistory> fetchByAction(String... values) {
        return fetch(MdDocumentHistory.MD_DOCUMENT_HISTORY.ACTION, values);
    }

    /**
     * Fetch records that have <code>action_name IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdDocumentHistory> fetchByActionName(String... values) {
        return fetch(MdDocumentHistory.MD_DOCUMENT_HISTORY.ACTION_NAME, values);
    }

    /**
     * Fetch records that have <code>document_id IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdDocumentHistory> fetchByDocumentId(Integer... values) {
        return fetch(MdDocumentHistory.MD_DOCUMENT_HISTORY.DOCUMENT_ID, values);
    }

    /**
     * Fetch records that have <code>document_name IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdDocumentHistory> fetchByDocumentName(String... values) {
        return fetch(MdDocumentHistory.MD_DOCUMENT_HISTORY.DOCUMENT_NAME, values);
    }

    /**
     * Fetch records that have <code>parent_id IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdDocumentHistory> fetchByParentId(Integer... values) {
        return fetch(MdDocumentHistory.MD_DOCUMENT_HISTORY.PARENT_ID, values);
    }

    /**
     * Fetch records that have <code>markdown IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdDocumentHistory> fetchByMarkdown(String... values) {
        return fetch(MdDocumentHistory.MD_DOCUMENT_HISTORY.MARKDOWN, values);
    }

    /**
     * Fetch records that have <code>content IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdDocumentHistory> fetchByContent(String... values) {
        return fetch(MdDocumentHistory.MD_DOCUMENT_HISTORY.CONTENT, values);
    }

    /**
     * Fetch records that have <code>member_id IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdDocumentHistory> fetchByMemberId(Integer... values) {
        return fetch(MdDocumentHistory.MD_DOCUMENT_HISTORY.MEMBER_ID, values);
    }

    /**
     * Fetch records that have <code>modify_time IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdDocumentHistory> fetchByModifyTime(Timestamp... values) {
        return fetch(MdDocumentHistory.MD_DOCUMENT_HISTORY.MODIFY_TIME, values);
    }

    /**
     * Fetch records that have <code>modify_at IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdDocumentHistory> fetchByModifyAt(Integer... values) {
        return fetch(MdDocumentHistory.MD_DOCUMENT_HISTORY.MODIFY_AT, values);
    }

    /**
     * Fetch records that have <code>version IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdDocumentHistory> fetchByVersion(Long... values) {
        return fetch(MdDocumentHistory.MD_DOCUMENT_HISTORY.VERSION, values);
    }
}
