/**
 * This class is generated by jOOQ
 */
package com.example.mindoc_transfer.db.pojo.tables.daos;


import com.example.mindoc_transfer.db.pojo.tables.MdLabel;
import com.example.mindoc_transfer.db.pojo.tables.records.MdLabelRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MdLabelDao extends DAOImpl<MdLabelRecord, com.example.mindoc_transfer.db.pojo.tables.pojos.MdLabel, Integer> {

    /**
     * Create a new MdLabelDao without any configuration
     */
    public MdLabelDao() {
        super(MdLabel.MD_LABEL, com.example.mindoc_transfer.db.pojo.tables.pojos.MdLabel.class);
    }

    /**
     * Create a new MdLabelDao with an attached configuration
     */
    public MdLabelDao(Configuration configuration) {
        super(MdLabel.MD_LABEL, com.example.mindoc_transfer.db.pojo.tables.pojos.MdLabel.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.example.mindoc_transfer.db.pojo.tables.pojos.MdLabel object) {
        return object.getLabelId();
    }

    /**
     * Fetch records that have <code>label_id IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdLabel> fetchByLabelId(Integer... values) {
        return fetch(MdLabel.MD_LABEL.LABEL_ID, values);
    }

    /**
     * Fetch a unique record that has <code>label_id = value</code>
     */
    public com.example.mindoc_transfer.db.pojo.tables.pojos.MdLabel fetchOneByLabelId(Integer value) {
        return fetchOne(MdLabel.MD_LABEL.LABEL_ID, value);
    }

    /**
     * Fetch records that have <code>label_name IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdLabel> fetchByLabelName(String... values) {
        return fetch(MdLabel.MD_LABEL.LABEL_NAME, values);
    }

    /**
     * Fetch a unique record that has <code>label_name = value</code>
     */
    public com.example.mindoc_transfer.db.pojo.tables.pojos.MdLabel fetchOneByLabelName(String value) {
        return fetchOne(MdLabel.MD_LABEL.LABEL_NAME, value);
    }

    /**
     * Fetch records that have <code>book_number IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdLabel> fetchByBookNumber(Integer... values) {
        return fetch(MdLabel.MD_LABEL.BOOK_NUMBER, values);
    }
}
