/**
 * This class is generated by jOOQ
 */
package com.example.mindoc_transfer.db.pojo.tables.daos;


import com.example.mindoc_transfer.db.pojo.tables.MdMemberToken;
import com.example.mindoc_transfer.db.pojo.tables.records.MdMemberTokenRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MdMemberTokenDao extends DAOImpl<MdMemberTokenRecord, com.example.mindoc_transfer.db.pojo.tables.pojos.MdMemberToken, Integer> {

    /**
     * Create a new MdMemberTokenDao without any configuration
     */
    public MdMemberTokenDao() {
        super(MdMemberToken.MD_MEMBER_TOKEN, com.example.mindoc_transfer.db.pojo.tables.pojos.MdMemberToken.class);
    }

    /**
     * Create a new MdMemberTokenDao with an attached configuration
     */
    public MdMemberTokenDao(Configuration configuration) {
        super(MdMemberToken.MD_MEMBER_TOKEN, com.example.mindoc_transfer.db.pojo.tables.pojos.MdMemberToken.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.example.mindoc_transfer.db.pojo.tables.pojos.MdMemberToken object) {
        return object.getTokenId();
    }

    /**
     * Fetch records that have <code>token_id IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdMemberToken> fetchByTokenId(Integer... values) {
        return fetch(MdMemberToken.MD_MEMBER_TOKEN.TOKEN_ID, values);
    }

    /**
     * Fetch a unique record that has <code>token_id = value</code>
     */
    public com.example.mindoc_transfer.db.pojo.tables.pojos.MdMemberToken fetchOneByTokenId(Integer value) {
        return fetchOne(MdMemberToken.MD_MEMBER_TOKEN.TOKEN_ID, value);
    }

    /**
     * Fetch records that have <code>member_id IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdMemberToken> fetchByMemberId(Integer... values) {
        return fetch(MdMemberToken.MD_MEMBER_TOKEN.MEMBER_ID, values);
    }

    /**
     * Fetch records that have <code>token IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdMemberToken> fetchByToken(String... values) {
        return fetch(MdMemberToken.MD_MEMBER_TOKEN.TOKEN, values);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdMemberToken> fetchByEmail(String... values) {
        return fetch(MdMemberToken.MD_MEMBER_TOKEN.EMAIL, values);
    }

    /**
     * Fetch records that have <code>is_valid IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdMemberToken> fetchByIsValid(Byte... values) {
        return fetch(MdMemberToken.MD_MEMBER_TOKEN.IS_VALID, values);
    }

    /**
     * Fetch records that have <code>valid_time IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdMemberToken> fetchByValidTime(Timestamp... values) {
        return fetch(MdMemberToken.MD_MEMBER_TOKEN.VALID_TIME, values);
    }

    /**
     * Fetch records that have <code>send_time IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdMemberToken> fetchBySendTime(Timestamp... values) {
        return fetch(MdMemberToken.MD_MEMBER_TOKEN.SEND_TIME, values);
    }
}
