/**
 * This class is generated by jOOQ
 */
package com.example.mindoc_transfer.db.pojo.tables.daos;


import com.example.mindoc_transfer.db.pojo.tables.MdOptions;
import com.example.mindoc_transfer.db.pojo.tables.records.MdOptionsRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MdOptionsDao extends DAOImpl<MdOptionsRecord, com.example.mindoc_transfer.db.pojo.tables.pojos.MdOptions, Integer> {

    /**
     * Create a new MdOptionsDao without any configuration
     */
    public MdOptionsDao() {
        super(MdOptions.MD_OPTIONS, com.example.mindoc_transfer.db.pojo.tables.pojos.MdOptions.class);
    }

    /**
     * Create a new MdOptionsDao with an attached configuration
     */
    public MdOptionsDao(Configuration configuration) {
        super(MdOptions.MD_OPTIONS, com.example.mindoc_transfer.db.pojo.tables.pojos.MdOptions.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.example.mindoc_transfer.db.pojo.tables.pojos.MdOptions object) {
        return object.getOptionId();
    }

    /**
     * Fetch records that have <code>option_id IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdOptions> fetchByOptionId(Integer... values) {
        return fetch(MdOptions.MD_OPTIONS.OPTION_ID, values);
    }

    /**
     * Fetch a unique record that has <code>option_id = value</code>
     */
    public com.example.mindoc_transfer.db.pojo.tables.pojos.MdOptions fetchOneByOptionId(Integer value) {
        return fetchOne(MdOptions.MD_OPTIONS.OPTION_ID, value);
    }

    /**
     * Fetch records that have <code>option_title IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdOptions> fetchByOptionTitle(String... values) {
        return fetch(MdOptions.MD_OPTIONS.OPTION_TITLE, values);
    }

    /**
     * Fetch records that have <code>option_name IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdOptions> fetchByOptionName(String... values) {
        return fetch(MdOptions.MD_OPTIONS.OPTION_NAME, values);
    }

    /**
     * Fetch a unique record that has <code>option_name = value</code>
     */
    public com.example.mindoc_transfer.db.pojo.tables.pojos.MdOptions fetchOneByOptionName(String value) {
        return fetchOne(MdOptions.MD_OPTIONS.OPTION_NAME, value);
    }

    /**
     * Fetch records that have <code>option_value IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdOptions> fetchByOptionValue(String... values) {
        return fetch(MdOptions.MD_OPTIONS.OPTION_VALUE, values);
    }

    /**
     * Fetch records that have <code>remark IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdOptions> fetchByRemark(String... values) {
        return fetch(MdOptions.MD_OPTIONS.REMARK, values);
    }
}
