/**
 * This class is generated by jOOQ
 */
package com.example.mindoc_transfer.db.pojo.tables.daos;


import com.example.mindoc_transfer.db.pojo.tables.MdRelationship;
import com.example.mindoc_transfer.db.pojo.tables.records.MdRelationshipRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MdRelationshipDao extends DAOImpl<MdRelationshipRecord, com.example.mindoc_transfer.db.pojo.tables.pojos.MdRelationship, Integer> {

    /**
     * Create a new MdRelationshipDao without any configuration
     */
    public MdRelationshipDao() {
        super(MdRelationship.MD_RELATIONSHIP, com.example.mindoc_transfer.db.pojo.tables.pojos.MdRelationship.class);
    }

    /**
     * Create a new MdRelationshipDao with an attached configuration
     */
    public MdRelationshipDao(Configuration configuration) {
        super(MdRelationship.MD_RELATIONSHIP, com.example.mindoc_transfer.db.pojo.tables.pojos.MdRelationship.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.example.mindoc_transfer.db.pojo.tables.pojos.MdRelationship object) {
        return object.getRelationshipId();
    }

    /**
     * Fetch records that have <code>relationship_id IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdRelationship> fetchByRelationshipId(Integer... values) {
        return fetch(MdRelationship.MD_RELATIONSHIP.RELATIONSHIP_ID, values);
    }

    /**
     * Fetch a unique record that has <code>relationship_id = value</code>
     */
    public com.example.mindoc_transfer.db.pojo.tables.pojos.MdRelationship fetchOneByRelationshipId(Integer value) {
        return fetchOne(MdRelationship.MD_RELATIONSHIP.RELATIONSHIP_ID, value);
    }

    /**
     * Fetch records that have <code>member_id IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdRelationship> fetchByMemberId(Integer... values) {
        return fetch(MdRelationship.MD_RELATIONSHIP.MEMBER_ID, values);
    }

    /**
     * Fetch records that have <code>book_id IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdRelationship> fetchByBookId(Integer... values) {
        return fetch(MdRelationship.MD_RELATIONSHIP.BOOK_ID, values);
    }

    /**
     * Fetch records that have <code>role_id IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.MdRelationship> fetchByRoleId(Integer... values) {
        return fetch(MdRelationship.MD_RELATIONSHIP.ROLE_ID, values);
    }
}
