/**
 * This class is generated by jOOQ
 */
package com.example.mindoc_transfer.db.pojo.tables.daos;


import com.example.mindoc_transfer.db.pojo.tables.OpcHelpCenterAttachments;
import com.example.mindoc_transfer.db.pojo.tables.records.OpcHelpCenterAttachmentsRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OpcHelpCenterAttachmentsDao extends DAOImpl<OpcHelpCenterAttachmentsRecord, com.example.mindoc_transfer.db.pojo.tables.pojos.OpcHelpCenterAttachments, Integer> {

    /**
     * Create a new OpcHelpCenterAttachmentsDao without any configuration
     */
    public OpcHelpCenterAttachmentsDao() {
        super(OpcHelpCenterAttachments.OPC_HELP_CENTER_ATTACHMENTS, com.example.mindoc_transfer.db.pojo.tables.pojos.OpcHelpCenterAttachments.class);
    }

    /**
     * Create a new OpcHelpCenterAttachmentsDao with an attached configuration
     */
    public OpcHelpCenterAttachmentsDao(Configuration configuration) {
        super(OpcHelpCenterAttachments.OPC_HELP_CENTER_ATTACHMENTS, com.example.mindoc_transfer.db.pojo.tables.pojos.OpcHelpCenterAttachments.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.example.mindoc_transfer.db.pojo.tables.pojos.OpcHelpCenterAttachments object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.OpcHelpCenterAttachments> fetchById(Integer... values) {
        return fetch(OpcHelpCenterAttachments.OPC_HELP_CENTER_ATTACHMENTS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.example.mindoc_transfer.db.pojo.tables.pojos.OpcHelpCenterAttachments fetchOneById(Integer value) {
        return fetchOne(OpcHelpCenterAttachments.OPC_HELP_CENTER_ATTACHMENTS.ID, value);
    }

    /**
     * Fetch records that have <code>folder_structure_id IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.OpcHelpCenterAttachments> fetchByFolderStructureId(Long... values) {
        return fetch(OpcHelpCenterAttachments.OPC_HELP_CENTER_ATTACHMENTS.FOLDER_STRUCTURE_ID, values);
    }

    /**
     * Fetch records that have <code>file_structure_id IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.OpcHelpCenterAttachments> fetchByFileStructureId(Integer... values) {
        return fetch(OpcHelpCenterAttachments.OPC_HELP_CENTER_ATTACHMENTS.FILE_STRUCTURE_ID, values);
    }

    /**
     * Fetch records that have <code>file_url IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.OpcHelpCenterAttachments> fetchByFileUrl(String... values) {
        return fetch(OpcHelpCenterAttachments.OPC_HELP_CENTER_ATTACHMENTS.FILE_URL, values);
    }

    /**
     * Fetch records that have <code>file_name IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.OpcHelpCenterAttachments> fetchByFileName(String... values) {
        return fetch(OpcHelpCenterAttachments.OPC_HELP_CENTER_ATTACHMENTS.FILE_NAME, values);
    }

    /**
     * Fetch records that have <code>file_path IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.OpcHelpCenterAttachments> fetchByFilePath(String... values) {
        return fetch(OpcHelpCenterAttachments.OPC_HELP_CENTER_ATTACHMENTS.FILE_PATH, values);
    }

    /**
     * Fetch records that have <code>file_size IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.OpcHelpCenterAttachments> fetchByFileSize(Double... values) {
        return fetch(OpcHelpCenterAttachments.OPC_HELP_CENTER_ATTACHMENTS.FILE_SIZE, values);
    }

    /**
     * Fetch records that have <code>http_path IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.OpcHelpCenterAttachments> fetchByHttpPath(String... values) {
        return fetch(OpcHelpCenterAttachments.OPC_HELP_CENTER_ATTACHMENTS.HTTP_PATH, values);
    }

    /**
     * Fetch records that have <code>file_ext IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.OpcHelpCenterAttachments> fetchByFileExt(String... values) {
        return fetch(OpcHelpCenterAttachments.OPC_HELP_CENTER_ATTACHMENTS.FILE_EXT, values);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.OpcHelpCenterAttachments> fetchByCreateTime(Timestamp... values) {
        return fetch(OpcHelpCenterAttachments.OPC_HELP_CENTER_ATTACHMENTS.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>create_at IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.OpcHelpCenterAttachments> fetchByCreateAt(Integer... values) {
        return fetch(OpcHelpCenterAttachments.OPC_HELP_CENTER_ATTACHMENTS.CREATE_AT, values);
    }
}
