/**
 * This class is generated by jOOQ
 */
package com.example.mindoc_transfer.db.pojo.tables.daos;


import com.example.mindoc_transfer.db.pojo.tables.OpcHelpCenterFilesStructures;
import com.example.mindoc_transfer.db.pojo.tables.records.OpcHelpCenterFilesStructuresRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 帮助中心：文档数据表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OpcHelpCenterFilesStructuresDao extends DAOImpl<OpcHelpCenterFilesStructuresRecord, com.example.mindoc_transfer.db.pojo.tables.pojos.OpcHelpCenterFilesStructures, Long> {

    /**
     * Create a new OpcHelpCenterFilesStructuresDao without any configuration
     */
    public OpcHelpCenterFilesStructuresDao() {
        super(OpcHelpCenterFilesStructures.OPC_HELP_CENTER_FILES_STRUCTURES, com.example.mindoc_transfer.db.pojo.tables.pojos.OpcHelpCenterFilesStructures.class);
    }

    /**
     * Create a new OpcHelpCenterFilesStructuresDao with an attached configuration
     */
    public OpcHelpCenterFilesStructuresDao(Configuration configuration) {
        super(OpcHelpCenterFilesStructures.OPC_HELP_CENTER_FILES_STRUCTURES, com.example.mindoc_transfer.db.pojo.tables.pojos.OpcHelpCenterFilesStructures.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.example.mindoc_transfer.db.pojo.tables.pojos.OpcHelpCenterFilesStructures object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.OpcHelpCenterFilesStructures> fetchById(Long... values) {
        return fetch(OpcHelpCenterFilesStructures.OPC_HELP_CENTER_FILES_STRUCTURES.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.example.mindoc_transfer.db.pojo.tables.pojos.OpcHelpCenterFilesStructures fetchOneById(Long value) {
        return fetchOne(OpcHelpCenterFilesStructures.OPC_HELP_CENTER_FILES_STRUCTURES.ID, value);
    }

    /**
     * Fetch records that have <code>folder_structure_id IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.OpcHelpCenterFilesStructures> fetchByFolderStructureId(Long... values) {
        return fetch(OpcHelpCenterFilesStructures.OPC_HELP_CENTER_FILES_STRUCTURES.FOLDER_STRUCTURE_ID, values);
    }

    /**
     * Fetch records that have <code>parent_id IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.OpcHelpCenterFilesStructures> fetchByParentId(Long... values) {
        return fetch(OpcHelpCenterFilesStructures.OPC_HELP_CENTER_FILES_STRUCTURES.PARENT_ID, values);
    }

    /**
     * Fetch records that have <code>level IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.OpcHelpCenterFilesStructures> fetchByLevel(Integer... values) {
        return fetch(OpcHelpCenterFilesStructures.OPC_HELP_CENTER_FILES_STRUCTURES.LEVEL, values);
    }

    /**
     * Fetch records that have <code>path IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.OpcHelpCenterFilesStructures> fetchByPath(String... values) {
        return fetch(OpcHelpCenterFilesStructures.OPC_HELP_CENTER_FILES_STRUCTURES.PATH, values);
    }

    /**
     * Fetch records that have <code>file_name IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.OpcHelpCenterFilesStructures> fetchByFileName(String... values) {
        return fetch(OpcHelpCenterFilesStructures.OPC_HELP_CENTER_FILES_STRUCTURES.FILE_NAME, values);
    }

    /**
     * Fetch records that have <code>sort_num IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.OpcHelpCenterFilesStructures> fetchBySortNum(Integer... values) {
        return fetch(OpcHelpCenterFilesStructures.OPC_HELP_CENTER_FILES_STRUCTURES.SORT_NUM, values);
    }

    /**
     * Fetch records that have <code>publish_type IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.OpcHelpCenterFilesStructures> fetchByPublishType(Byte... values) {
        return fetch(OpcHelpCenterFilesStructures.OPC_HELP_CENTER_FILES_STRUCTURES.PUBLISH_TYPE, values);
    }

    /**
     * Fetch records that have <code>publish_version_identify IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.OpcHelpCenterFilesStructures> fetchByPublishVersionIdentify(String... values) {
        return fetch(OpcHelpCenterFilesStructures.OPC_HELP_CENTER_FILES_STRUCTURES.PUBLISH_VERSION_IDENTIFY, values);
    }

    /**
     * Fetch records that have <code>publish_version_number IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.OpcHelpCenterFilesStructures> fetchByPublishVersionNumber(String... values) {
        return fetch(OpcHelpCenterFilesStructures.OPC_HELP_CENTER_FILES_STRUCTURES.PUBLISH_VERSION_NUMBER, values);
    }

    /**
     * Fetch records that have <code>draft_flag IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.OpcHelpCenterFilesStructures> fetchByDraftFlag(Byte... values) {
        return fetch(OpcHelpCenterFilesStructures.OPC_HELP_CENTER_FILES_STRUCTURES.DRAFT_FLAG, values);
    }

    /**
     * Fetch records that have <code>last_commit IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.OpcHelpCenterFilesStructures> fetchByLastCommit(String... values) {
        return fetch(OpcHelpCenterFilesStructures.OPC_HELP_CENTER_FILES_STRUCTURES.LAST_COMMIT, values);
    }

    /**
     * Fetch records that have <code>namespace_id IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.OpcHelpCenterFilesStructures> fetchByNamespaceId(Integer... values) {
        return fetch(OpcHelpCenterFilesStructures.OPC_HELP_CENTER_FILES_STRUCTURES.NAMESPACE_ID, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.OpcHelpCenterFilesStructures> fetchByStatus(Byte... values) {
        return fetch(OpcHelpCenterFilesStructures.OPC_HELP_CENTER_FILES_STRUCTURES.STATUS, values);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.OpcHelpCenterFilesStructures> fetchByCreateTime(Timestamp... values) {
        return fetch(OpcHelpCenterFilesStructures.OPC_HELP_CENTER_FILES_STRUCTURES.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>creator_uid IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.OpcHelpCenterFilesStructures> fetchByCreatorUid(Long... values) {
        return fetch(OpcHelpCenterFilesStructures.OPC_HELP_CENTER_FILES_STRUCTURES.CREATOR_UID, values);
    }

    /**
     * Fetch records that have <code>update_time IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.OpcHelpCenterFilesStructures> fetchByUpdateTime(Timestamp... values) {
        return fetch(OpcHelpCenterFilesStructures.OPC_HELP_CENTER_FILES_STRUCTURES.UPDATE_TIME, values);
    }

    /**
     * Fetch records that have <code>updator_uid IN (values)</code>
     */
    public List<com.example.mindoc_transfer.db.pojo.tables.pojos.OpcHelpCenterFilesStructures> fetchByUpdatorUid(Long... values) {
        return fetch(OpcHelpCenterFilesStructures.OPC_HELP_CENTER_FILES_STRUCTURES.UPDATOR_UID, values);
    }
}
