/**
 * This class is generated by jOOQ
 */
package com.example.mindoc_transfer.db.pojo;


import com.example.mindoc_transfer.db.pojo.tables.MdAttachment;
import com.example.mindoc_transfer.db.pojo.tables.MdBooks;
import com.example.mindoc_transfer.db.pojo.tables.MdDocumentHistory;
import com.example.mindoc_transfer.db.pojo.tables.MdDocuments;
import com.example.mindoc_transfer.db.pojo.tables.MdLabel;
import com.example.mindoc_transfer.db.pojo.tables.MdLogs;
import com.example.mindoc_transfer.db.pojo.tables.MdMemberToken;
import com.example.mindoc_transfer.db.pojo.tables.MdMembers;
import com.example.mindoc_transfer.db.pojo.tables.MdMigrations;
import com.example.mindoc_transfer.db.pojo.tables.MdOptions;
import com.example.mindoc_transfer.db.pojo.tables.MdRelationship;
import com.example.mindoc_transfer.db.pojo.tables.OpcHelpCenterFilesStructures;
import com.example.mindoc_transfer.db.pojo.tables.OpcHelpCenterFoldersStructures;
import com.example.mindoc_transfer.db.pojo.tables.records.MdAttachmentRecord;
import com.example.mindoc_transfer.db.pojo.tables.records.MdBooksRecord;
import com.example.mindoc_transfer.db.pojo.tables.records.MdDocumentHistoryRecord;
import com.example.mindoc_transfer.db.pojo.tables.records.MdDocumentsRecord;
import com.example.mindoc_transfer.db.pojo.tables.records.MdLabelRecord;
import com.example.mindoc_transfer.db.pojo.tables.records.MdLogsRecord;
import com.example.mindoc_transfer.db.pojo.tables.records.MdMemberTokenRecord;
import com.example.mindoc_transfer.db.pojo.tables.records.MdMembersRecord;
import com.example.mindoc_transfer.db.pojo.tables.records.MdMigrationsRecord;
import com.example.mindoc_transfer.db.pojo.tables.records.MdOptionsRecord;
import com.example.mindoc_transfer.db.pojo.tables.records.MdRelationshipRecord;
import com.example.mindoc_transfer.db.pojo.tables.records.OpcHelpCenterFilesStructuresRecord;
import com.example.mindoc_transfer.db.pojo.tables.records.OpcHelpCenterFoldersStructuresRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>mindoc_db</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<MdAttachmentRecord, Integer> IDENTITY_MD_ATTACHMENT = Identities0.IDENTITY_MD_ATTACHMENT;
    public static final Identity<MdBooksRecord, Integer> IDENTITY_MD_BOOKS = Identities0.IDENTITY_MD_BOOKS;
    public static final Identity<MdDocumentsRecord, Integer> IDENTITY_MD_DOCUMENTS = Identities0.IDENTITY_MD_DOCUMENTS;
    public static final Identity<MdDocumentHistoryRecord, Integer> IDENTITY_MD_DOCUMENT_HISTORY = Identities0.IDENTITY_MD_DOCUMENT_HISTORY;
    public static final Identity<MdLabelRecord, Integer> IDENTITY_MD_LABEL = Identities0.IDENTITY_MD_LABEL;
    public static final Identity<MdLogsRecord, Long> IDENTITY_MD_LOGS = Identities0.IDENTITY_MD_LOGS;
    public static final Identity<MdMembersRecord, Integer> IDENTITY_MD_MEMBERS = Identities0.IDENTITY_MD_MEMBERS;
    public static final Identity<MdMemberTokenRecord, Integer> IDENTITY_MD_MEMBER_TOKEN = Identities0.IDENTITY_MD_MEMBER_TOKEN;
    public static final Identity<MdMigrationsRecord, Integer> IDENTITY_MD_MIGRATIONS = Identities0.IDENTITY_MD_MIGRATIONS;
    public static final Identity<MdOptionsRecord, Integer> IDENTITY_MD_OPTIONS = Identities0.IDENTITY_MD_OPTIONS;
    public static final Identity<MdRelationshipRecord, Integer> IDENTITY_MD_RELATIONSHIP = Identities0.IDENTITY_MD_RELATIONSHIP;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<MdAttachmentRecord> KEY_MD_ATTACHMENT_PRIMARY = UniqueKeys0.KEY_MD_ATTACHMENT_PRIMARY;
    public static final UniqueKey<MdBooksRecord> KEY_MD_BOOKS_PRIMARY = UniqueKeys0.KEY_MD_BOOKS_PRIMARY;
    public static final UniqueKey<MdBooksRecord> KEY_MD_BOOKS_IDENTIFY = UniqueKeys0.KEY_MD_BOOKS_IDENTIFY;
    public static final UniqueKey<MdDocumentsRecord> KEY_MD_DOCUMENTS_PRIMARY = UniqueKeys0.KEY_MD_DOCUMENTS_PRIMARY;
    public static final UniqueKey<MdDocumentHistoryRecord> KEY_MD_DOCUMENT_HISTORY_PRIMARY = UniqueKeys0.KEY_MD_DOCUMENT_HISTORY_PRIMARY;
    public static final UniqueKey<MdLabelRecord> KEY_MD_LABEL_PRIMARY = UniqueKeys0.KEY_MD_LABEL_PRIMARY;
    public static final UniqueKey<MdLabelRecord> KEY_MD_LABEL_LABEL_NAME = UniqueKeys0.KEY_MD_LABEL_LABEL_NAME;
    public static final UniqueKey<MdLogsRecord> KEY_MD_LOGS_PRIMARY = UniqueKeys0.KEY_MD_LOGS_PRIMARY;
    public static final UniqueKey<MdMembersRecord> KEY_MD_MEMBERS_PRIMARY = UniqueKeys0.KEY_MD_MEMBERS_PRIMARY;
    public static final UniqueKey<MdMembersRecord> KEY_MD_MEMBERS_ACCOUNT = UniqueKeys0.KEY_MD_MEMBERS_ACCOUNT;
    public static final UniqueKey<MdMembersRecord> KEY_MD_MEMBERS_EMAIL = UniqueKeys0.KEY_MD_MEMBERS_EMAIL;
    public static final UniqueKey<MdMemberTokenRecord> KEY_MD_MEMBER_TOKEN_PRIMARY = UniqueKeys0.KEY_MD_MEMBER_TOKEN_PRIMARY;
    public static final UniqueKey<MdMigrationsRecord> KEY_MD_MIGRATIONS_PRIMARY = UniqueKeys0.KEY_MD_MIGRATIONS_PRIMARY;
    public static final UniqueKey<MdMigrationsRecord> KEY_MD_MIGRATIONS_VERSION = UniqueKeys0.KEY_MD_MIGRATIONS_VERSION;
    public static final UniqueKey<MdOptionsRecord> KEY_MD_OPTIONS_PRIMARY = UniqueKeys0.KEY_MD_OPTIONS_PRIMARY;
    public static final UniqueKey<MdOptionsRecord> KEY_MD_OPTIONS_OPTION_NAME = UniqueKeys0.KEY_MD_OPTIONS_OPTION_NAME;
    public static final UniqueKey<MdRelationshipRecord> KEY_MD_RELATIONSHIP_PRIMARY = UniqueKeys0.KEY_MD_RELATIONSHIP_PRIMARY;
    public static final UniqueKey<MdRelationshipRecord> KEY_MD_RELATIONSHIP_MEMBER_ID = UniqueKeys0.KEY_MD_RELATIONSHIP_MEMBER_ID;
    public static final UniqueKey<OpcHelpCenterFilesStructuresRecord> KEY_OPC_HELP_CENTER_FILES_STRUCTURES_PRIMARY = UniqueKeys0.KEY_OPC_HELP_CENTER_FILES_STRUCTURES_PRIMARY;
    public static final UniqueKey<OpcHelpCenterFoldersStructuresRecord> KEY_OPC_HELP_CENTER_FOLDERS_STRUCTURES_PRIMARY = UniqueKeys0.KEY_OPC_HELP_CENTER_FOLDERS_STRUCTURES_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<MdAttachmentRecord, Integer> IDENTITY_MD_ATTACHMENT = createIdentity(MdAttachment.MD_ATTACHMENT, MdAttachment.MD_ATTACHMENT.ATTACHMENT_ID);
        public static Identity<MdBooksRecord, Integer> IDENTITY_MD_BOOKS = createIdentity(MdBooks.MD_BOOKS, MdBooks.MD_BOOKS.BOOK_ID);
        public static Identity<MdDocumentsRecord, Integer> IDENTITY_MD_DOCUMENTS = createIdentity(MdDocuments.MD_DOCUMENTS, MdDocuments.MD_DOCUMENTS.DOCUMENT_ID);
        public static Identity<MdDocumentHistoryRecord, Integer> IDENTITY_MD_DOCUMENT_HISTORY = createIdentity(MdDocumentHistory.MD_DOCUMENT_HISTORY, MdDocumentHistory.MD_DOCUMENT_HISTORY.HISTORY_ID);
        public static Identity<MdLabelRecord, Integer> IDENTITY_MD_LABEL = createIdentity(MdLabel.MD_LABEL, MdLabel.MD_LABEL.LABEL_ID);
        public static Identity<MdLogsRecord, Long> IDENTITY_MD_LOGS = createIdentity(MdLogs.MD_LOGS, MdLogs.MD_LOGS.LOG_ID);
        public static Identity<MdMembersRecord, Integer> IDENTITY_MD_MEMBERS = createIdentity(MdMembers.MD_MEMBERS, MdMembers.MD_MEMBERS.MEMBER_ID);
        public static Identity<MdMemberTokenRecord, Integer> IDENTITY_MD_MEMBER_TOKEN = createIdentity(MdMemberToken.MD_MEMBER_TOKEN, MdMemberToken.MD_MEMBER_TOKEN.TOKEN_ID);
        public static Identity<MdMigrationsRecord, Integer> IDENTITY_MD_MIGRATIONS = createIdentity(MdMigrations.MD_MIGRATIONS, MdMigrations.MD_MIGRATIONS.MIGRATION_ID);
        public static Identity<MdOptionsRecord, Integer> IDENTITY_MD_OPTIONS = createIdentity(MdOptions.MD_OPTIONS, MdOptions.MD_OPTIONS.OPTION_ID);
        public static Identity<MdRelationshipRecord, Integer> IDENTITY_MD_RELATIONSHIP = createIdentity(MdRelationship.MD_RELATIONSHIP, MdRelationship.MD_RELATIONSHIP.RELATIONSHIP_ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<MdAttachmentRecord> KEY_MD_ATTACHMENT_PRIMARY = createUniqueKey(MdAttachment.MD_ATTACHMENT, "KEY_md_attachment_PRIMARY", MdAttachment.MD_ATTACHMENT.ATTACHMENT_ID);
        public static final UniqueKey<MdBooksRecord> KEY_MD_BOOKS_PRIMARY = createUniqueKey(MdBooks.MD_BOOKS, "KEY_md_books_PRIMARY", MdBooks.MD_BOOKS.BOOK_ID);
        public static final UniqueKey<MdBooksRecord> KEY_MD_BOOKS_IDENTIFY = createUniqueKey(MdBooks.MD_BOOKS, "KEY_md_books_identify", MdBooks.MD_BOOKS.IDENTIFY);
        public static final UniqueKey<MdDocumentsRecord> KEY_MD_DOCUMENTS_PRIMARY = createUniqueKey(MdDocuments.MD_DOCUMENTS, "KEY_md_documents_PRIMARY", MdDocuments.MD_DOCUMENTS.DOCUMENT_ID);
        public static final UniqueKey<MdDocumentHistoryRecord> KEY_MD_DOCUMENT_HISTORY_PRIMARY = createUniqueKey(MdDocumentHistory.MD_DOCUMENT_HISTORY, "KEY_md_document_history_PRIMARY", MdDocumentHistory.MD_DOCUMENT_HISTORY.HISTORY_ID);
        public static final UniqueKey<MdLabelRecord> KEY_MD_LABEL_PRIMARY = createUniqueKey(MdLabel.MD_LABEL, "KEY_md_label_PRIMARY", MdLabel.MD_LABEL.LABEL_ID);
        public static final UniqueKey<MdLabelRecord> KEY_MD_LABEL_LABEL_NAME = createUniqueKey(MdLabel.MD_LABEL, "KEY_md_label_label_name", MdLabel.MD_LABEL.LABEL_NAME);
        public static final UniqueKey<MdLogsRecord> KEY_MD_LOGS_PRIMARY = createUniqueKey(MdLogs.MD_LOGS, "KEY_md_logs_PRIMARY", MdLogs.MD_LOGS.LOG_ID);
        public static final UniqueKey<MdMembersRecord> KEY_MD_MEMBERS_PRIMARY = createUniqueKey(MdMembers.MD_MEMBERS, "KEY_md_members_PRIMARY", MdMembers.MD_MEMBERS.MEMBER_ID);
        public static final UniqueKey<MdMembersRecord> KEY_MD_MEMBERS_ACCOUNT = createUniqueKey(MdMembers.MD_MEMBERS, "KEY_md_members_account", MdMembers.MD_MEMBERS.ACCOUNT);
        public static final UniqueKey<MdMembersRecord> KEY_MD_MEMBERS_EMAIL = createUniqueKey(MdMembers.MD_MEMBERS, "KEY_md_members_email", MdMembers.MD_MEMBERS.EMAIL);
        public static final UniqueKey<MdMemberTokenRecord> KEY_MD_MEMBER_TOKEN_PRIMARY = createUniqueKey(MdMemberToken.MD_MEMBER_TOKEN, "KEY_md_member_token_PRIMARY", MdMemberToken.MD_MEMBER_TOKEN.TOKEN_ID);
        public static final UniqueKey<MdMigrationsRecord> KEY_MD_MIGRATIONS_PRIMARY = createUniqueKey(MdMigrations.MD_MIGRATIONS, "KEY_md_migrations_PRIMARY", MdMigrations.MD_MIGRATIONS.MIGRATION_ID);
        public static final UniqueKey<MdMigrationsRecord> KEY_MD_MIGRATIONS_VERSION = createUniqueKey(MdMigrations.MD_MIGRATIONS, "KEY_md_migrations_version", MdMigrations.MD_MIGRATIONS.VERSION);
        public static final UniqueKey<MdOptionsRecord> KEY_MD_OPTIONS_PRIMARY = createUniqueKey(MdOptions.MD_OPTIONS, "KEY_md_options_PRIMARY", MdOptions.MD_OPTIONS.OPTION_ID);
        public static final UniqueKey<MdOptionsRecord> KEY_MD_OPTIONS_OPTION_NAME = createUniqueKey(MdOptions.MD_OPTIONS, "KEY_md_options_option_name", MdOptions.MD_OPTIONS.OPTION_NAME);
        public static final UniqueKey<MdRelationshipRecord> KEY_MD_RELATIONSHIP_PRIMARY = createUniqueKey(MdRelationship.MD_RELATIONSHIP, "KEY_md_relationship_PRIMARY", MdRelationship.MD_RELATIONSHIP.RELATIONSHIP_ID);
        public static final UniqueKey<MdRelationshipRecord> KEY_MD_RELATIONSHIP_MEMBER_ID = createUniqueKey(MdRelationship.MD_RELATIONSHIP, "KEY_md_relationship_member_id", MdRelationship.MD_RELATIONSHIP.MEMBER_ID, MdRelationship.MD_RELATIONSHIP.BOOK_ID);
        public static final UniqueKey<OpcHelpCenterFilesStructuresRecord> KEY_OPC_HELP_CENTER_FILES_STRUCTURES_PRIMARY = createUniqueKey(OpcHelpCenterFilesStructures.OPC_HELP_CENTER_FILES_STRUCTURES, "KEY_opc_help_center_files_structures_PRIMARY", OpcHelpCenterFilesStructures.OPC_HELP_CENTER_FILES_STRUCTURES.ID);
        public static final UniqueKey<OpcHelpCenterFoldersStructuresRecord> KEY_OPC_HELP_CENTER_FOLDERS_STRUCTURES_PRIMARY = createUniqueKey(OpcHelpCenterFoldersStructures.OPC_HELP_CENTER_FOLDERS_STRUCTURES, "KEY_opc_help_center_folders_structures_PRIMARY", OpcHelpCenterFoldersStructures.OPC_HELP_CENTER_FOLDERS_STRUCTURES.ID);
    }
}
