/**
 * This class is generated by jOOQ
 */
package com.example.mindoc_transfer.db.pojo;


import com.example.mindoc_transfer.db.pojo.tables.MdAttachment;
import com.example.mindoc_transfer.db.pojo.tables.MdBooks;
import com.example.mindoc_transfer.db.pojo.tables.MdDocumentHistory;
import com.example.mindoc_transfer.db.pojo.tables.MdDocuments;
import com.example.mindoc_transfer.db.pojo.tables.MdLabel;
import com.example.mindoc_transfer.db.pojo.tables.MdLogs;
import com.example.mindoc_transfer.db.pojo.tables.MdMemberToken;
import com.example.mindoc_transfer.db.pojo.tables.MdMembers;
import com.example.mindoc_transfer.db.pojo.tables.MdMigrations;
import com.example.mindoc_transfer.db.pojo.tables.MdOptions;
import com.example.mindoc_transfer.db.pojo.tables.MdRelationship;
import com.example.mindoc_transfer.db.pojo.tables.OpcHelpCenterAttachments;
import com.example.mindoc_transfer.db.pojo.tables.OpcHelpCenterFilesStructures;
import com.example.mindoc_transfer.db.pojo.tables.OpcHelpCenterFoldersStructures;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MindocDb extends SchemaImpl {

    private static final long serialVersionUID = -562551409;

    /**
     * The reference instance of <code>mindoc_db</code>
     */
    public static final MindocDb MINDOC_DB = new MindocDb();

    /**
     * The table <code>mindoc_db.md_attachment</code>.
     */
    public final MdAttachment MD_ATTACHMENT = com.example.mindoc_transfer.db.pojo.tables.MdAttachment.MD_ATTACHMENT;

    /**
     * The table <code>mindoc_db.md_books</code>.
     */
    public final MdBooks MD_BOOKS = com.example.mindoc_transfer.db.pojo.tables.MdBooks.MD_BOOKS;

    /**
     * The table <code>mindoc_db.md_documents</code>.
     */
    public final MdDocuments MD_DOCUMENTS = com.example.mindoc_transfer.db.pojo.tables.MdDocuments.MD_DOCUMENTS;

    /**
     * The table <code>mindoc_db.md_document_history</code>.
     */
    public final MdDocumentHistory MD_DOCUMENT_HISTORY = com.example.mindoc_transfer.db.pojo.tables.MdDocumentHistory.MD_DOCUMENT_HISTORY;

    /**
     * The table <code>mindoc_db.md_label</code>.
     */
    public final MdLabel MD_LABEL = com.example.mindoc_transfer.db.pojo.tables.MdLabel.MD_LABEL;

    /**
     * The table <code>mindoc_db.md_logs</code>.
     */
    public final MdLogs MD_LOGS = com.example.mindoc_transfer.db.pojo.tables.MdLogs.MD_LOGS;

    /**
     * The table <code>mindoc_db.md_members</code>.
     */
    public final MdMembers MD_MEMBERS = com.example.mindoc_transfer.db.pojo.tables.MdMembers.MD_MEMBERS;

    /**
     * The table <code>mindoc_db.md_member_token</code>.
     */
    public final MdMemberToken MD_MEMBER_TOKEN = com.example.mindoc_transfer.db.pojo.tables.MdMemberToken.MD_MEMBER_TOKEN;

    /**
     * The table <code>mindoc_db.md_migrations</code>.
     */
    public final MdMigrations MD_MIGRATIONS = com.example.mindoc_transfer.db.pojo.tables.MdMigrations.MD_MIGRATIONS;

    /**
     * The table <code>mindoc_db.md_options</code>.
     */
    public final MdOptions MD_OPTIONS = com.example.mindoc_transfer.db.pojo.tables.MdOptions.MD_OPTIONS;

    /**
     * The table <code>mindoc_db.md_relationship</code>.
     */
    public final MdRelationship MD_RELATIONSHIP = com.example.mindoc_transfer.db.pojo.tables.MdRelationship.MD_RELATIONSHIP;

    /**
     * The table <code>mindoc_db.opc_help_center_attachments</code>.
     */
    public final OpcHelpCenterAttachments OPC_HELP_CENTER_ATTACHMENTS = com.example.mindoc_transfer.db.pojo.tables.OpcHelpCenterAttachments.OPC_HELP_CENTER_ATTACHMENTS;

    /**
     * 帮助中心：文档数据表
     */
    public final OpcHelpCenterFilesStructures OPC_HELP_CENTER_FILES_STRUCTURES = com.example.mindoc_transfer.db.pojo.tables.OpcHelpCenterFilesStructures.OPC_HELP_CENTER_FILES_STRUCTURES;

    /**
     * 帮助中心：帮助中心目录结构表
     */
    public final OpcHelpCenterFoldersStructures OPC_HELP_CENTER_FOLDERS_STRUCTURES = com.example.mindoc_transfer.db.pojo.tables.OpcHelpCenterFoldersStructures.OPC_HELP_CENTER_FOLDERS_STRUCTURES;

    /**
     * No further instances allowed
     */
    private MindocDb() {
        super("mindoc_db", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            MdAttachment.MD_ATTACHMENT,
            MdBooks.MD_BOOKS,
            MdDocuments.MD_DOCUMENTS,
            MdDocumentHistory.MD_DOCUMENT_HISTORY,
            MdLabel.MD_LABEL,
            MdLogs.MD_LOGS,
            MdMembers.MD_MEMBERS,
            MdMemberToken.MD_MEMBER_TOKEN,
            MdMigrations.MD_MIGRATIONS,
            MdOptions.MD_OPTIONS,
            MdRelationship.MD_RELATIONSHIP,
            OpcHelpCenterAttachments.OPC_HELP_CENTER_ATTACHMENTS,
            OpcHelpCenterFilesStructures.OPC_HELP_CENTER_FILES_STRUCTURES,
            OpcHelpCenterFoldersStructures.OPC_HELP_CENTER_FOLDERS_STRUCTURES);
    }
}
