/**
 * This class is generated by jOOQ
 */
package com.example.mindoc_transfer.db.pojo;


import com.example.mindoc_transfer.db.pojo.tables.MdAttachment;
import com.example.mindoc_transfer.db.pojo.tables.MdBooks;
import com.example.mindoc_transfer.db.pojo.tables.MdDocumentHistory;
import com.example.mindoc_transfer.db.pojo.tables.MdDocuments;
import com.example.mindoc_transfer.db.pojo.tables.MdLabel;
import com.example.mindoc_transfer.db.pojo.tables.MdLogs;
import com.example.mindoc_transfer.db.pojo.tables.MdMemberToken;
import com.example.mindoc_transfer.db.pojo.tables.MdMembers;
import com.example.mindoc_transfer.db.pojo.tables.MdMigrations;
import com.example.mindoc_transfer.db.pojo.tables.MdOptions;
import com.example.mindoc_transfer.db.pojo.tables.MdRelationship;
import com.example.mindoc_transfer.db.pojo.tables.OpcHelpCenterAttachments;
import com.example.mindoc_transfer.db.pojo.tables.OpcHelpCenterFilesStructures;
import com.example.mindoc_transfer.db.pojo.tables.OpcHelpCenterFoldersStructures;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in mindoc_db
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>mindoc_db.md_attachment</code>.
     */
    public static final MdAttachment MD_ATTACHMENT = com.example.mindoc_transfer.db.pojo.tables.MdAttachment.MD_ATTACHMENT;

    /**
     * The table <code>mindoc_db.md_books</code>.
     */
    public static final MdBooks MD_BOOKS = com.example.mindoc_transfer.db.pojo.tables.MdBooks.MD_BOOKS;

    /**
     * The table <code>mindoc_db.md_documents</code>.
     */
    public static final MdDocuments MD_DOCUMENTS = com.example.mindoc_transfer.db.pojo.tables.MdDocuments.MD_DOCUMENTS;

    /**
     * The table <code>mindoc_db.md_document_history</code>.
     */
    public static final MdDocumentHistory MD_DOCUMENT_HISTORY = com.example.mindoc_transfer.db.pojo.tables.MdDocumentHistory.MD_DOCUMENT_HISTORY;

    /**
     * The table <code>mindoc_db.md_label</code>.
     */
    public static final MdLabel MD_LABEL = com.example.mindoc_transfer.db.pojo.tables.MdLabel.MD_LABEL;

    /**
     * The table <code>mindoc_db.md_logs</code>.
     */
    public static final MdLogs MD_LOGS = com.example.mindoc_transfer.db.pojo.tables.MdLogs.MD_LOGS;

    /**
     * The table <code>mindoc_db.md_members</code>.
     */
    public static final MdMembers MD_MEMBERS = com.example.mindoc_transfer.db.pojo.tables.MdMembers.MD_MEMBERS;

    /**
     * The table <code>mindoc_db.md_member_token</code>.
     */
    public static final MdMemberToken MD_MEMBER_TOKEN = com.example.mindoc_transfer.db.pojo.tables.MdMemberToken.MD_MEMBER_TOKEN;

    /**
     * The table <code>mindoc_db.md_migrations</code>.
     */
    public static final MdMigrations MD_MIGRATIONS = com.example.mindoc_transfer.db.pojo.tables.MdMigrations.MD_MIGRATIONS;

    /**
     * The table <code>mindoc_db.md_options</code>.
     */
    public static final MdOptions MD_OPTIONS = com.example.mindoc_transfer.db.pojo.tables.MdOptions.MD_OPTIONS;

    /**
     * The table <code>mindoc_db.md_relationship</code>.
     */
    public static final MdRelationship MD_RELATIONSHIP = com.example.mindoc_transfer.db.pojo.tables.MdRelationship.MD_RELATIONSHIP;

    /**
     * The table <code>mindoc_db.opc_help_center_attachments</code>.
     */
    public static final OpcHelpCenterAttachments OPC_HELP_CENTER_ATTACHMENTS = com.example.mindoc_transfer.db.pojo.tables.OpcHelpCenterAttachments.OPC_HELP_CENTER_ATTACHMENTS;

    /**
     * 帮助中心：文档数据表
     */
    public static final OpcHelpCenterFilesStructures OPC_HELP_CENTER_FILES_STRUCTURES = com.example.mindoc_transfer.db.pojo.tables.OpcHelpCenterFilesStructures.OPC_HELP_CENTER_FILES_STRUCTURES;

    /**
     * 帮助中心：帮助中心目录结构表
     */
    public static final OpcHelpCenterFoldersStructures OPC_HELP_CENTER_FOLDERS_STRUCTURES = com.example.mindoc_transfer.db.pojo.tables.OpcHelpCenterFoldersStructures.OPC_HELP_CENTER_FOLDERS_STRUCTURES;
}
