/**
 * This class is generated by jOOQ
 */
package com.example.mindoc_transfer.db.pojo.tables.records;


import com.example.mindoc_transfer.db.pojo.tables.MdAttachment;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MdAttachmentRecord extends UpdatableRecordImpl<MdAttachmentRecord> implements Record10<Integer, Integer, Integer, String, String, Double, String, String, Timestamp, Integer> {

    private static final long serialVersionUID = 1793962593;

    /**
     * Setter for <code>mindoc_db.md_attachment.attachment_id</code>.
     */
    public void setAttachmentId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>mindoc_db.md_attachment.attachment_id</code>.
     */
    public Integer getAttachmentId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>mindoc_db.md_attachment.book_id</code>.
     */
    public void setBookId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>mindoc_db.md_attachment.book_id</code>.
     */
    public Integer getBookId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>mindoc_db.md_attachment.document_id</code>.
     */
    public void setDocumentId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>mindoc_db.md_attachment.document_id</code>.
     */
    public Integer getDocumentId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>mindoc_db.md_attachment.file_name</code>.
     */
    public void setFileName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mindoc_db.md_attachment.file_name</code>.
     */
    public String getFileName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mindoc_db.md_attachment.file_path</code>.
     */
    public void setFilePath(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>mindoc_db.md_attachment.file_path</code>.
     */
    public String getFilePath() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mindoc_db.md_attachment.file_size</code>.
     */
    public void setFileSize(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>mindoc_db.md_attachment.file_size</code>.
     */
    public Double getFileSize() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>mindoc_db.md_attachment.http_path</code>.
     */
    public void setHttpPath(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>mindoc_db.md_attachment.http_path</code>.
     */
    public String getHttpPath() {
        return (String) get(6);
    }

    /**
     * Setter for <code>mindoc_db.md_attachment.file_ext</code>.
     */
    public void setFileExt(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>mindoc_db.md_attachment.file_ext</code>.
     */
    public String getFileExt() {
        return (String) get(7);
    }

    /**
     * Setter for <code>mindoc_db.md_attachment.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>mindoc_db.md_attachment.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>mindoc_db.md_attachment.create_at</code>.
     */
    public void setCreateAt(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>mindoc_db.md_attachment.create_at</code>.
     */
    public Integer getCreateAt() {
        return (Integer) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, Integer, Integer, String, String, Double, String, String, Timestamp, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, Integer, Integer, String, String, Double, String, String, Timestamp, Integer> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return MdAttachment.MD_ATTACHMENT.ATTACHMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return MdAttachment.MD_ATTACHMENT.BOOK_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return MdAttachment.MD_ATTACHMENT.DOCUMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return MdAttachment.MD_ATTACHMENT.FILE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return MdAttachment.MD_ATTACHMENT.FILE_PATH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field6() {
        return MdAttachment.MD_ATTACHMENT.FILE_SIZE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return MdAttachment.MD_ATTACHMENT.HTTP_PATH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return MdAttachment.MD_ATTACHMENT.FILE_EXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return MdAttachment.MD_ATTACHMENT.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return MdAttachment.MD_ATTACHMENT.CREATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getAttachmentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getBookId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getDocumentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getFileName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getFilePath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value6() {
        return getFileSize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getHttpPath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getFileExt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdAttachmentRecord value1(Integer value) {
        setAttachmentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdAttachmentRecord value2(Integer value) {
        setBookId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdAttachmentRecord value3(Integer value) {
        setDocumentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdAttachmentRecord value4(String value) {
        setFileName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdAttachmentRecord value5(String value) {
        setFilePath(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdAttachmentRecord value6(Double value) {
        setFileSize(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdAttachmentRecord value7(String value) {
        setHttpPath(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdAttachmentRecord value8(String value) {
        setFileExt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdAttachmentRecord value9(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdAttachmentRecord value10(Integer value) {
        setCreateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdAttachmentRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5, Double value6, String value7, String value8, Timestamp value9, Integer value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    @Override
    public Integer component1() {
        return null;
    }

    @Override
    public Integer component2() {
        return null;
    }

    @Override
    public Integer component3() {
        return null;
    }

    @Override
    public String component4() {
        return null;
    }

    @Override
    public String component5() {
        return null;
    }

    @Override
    public Double component6() {
        return null;
    }

    @Override
    public String component7() {
        return null;
    }

    @Override
    public String component8() {
        return null;
    }

    @Override
    public Timestamp component9() {
        return null;
    }

    @Override
    public Integer component10() {
        return null;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MdAttachmentRecord
     */
    public MdAttachmentRecord() {
        super(MdAttachment.MD_ATTACHMENT);
    }

    /**
     * Create a detached, initialised MdAttachmentRecord
     */
    public MdAttachmentRecord(Integer attachmentId, Integer bookId, Integer documentId, String fileName, String filePath, Double fileSize, String httpPath, String fileExt, Timestamp createTime, Integer createAt) {
        super(MdAttachment.MD_ATTACHMENT);

        set(0, attachmentId);
        set(1, bookId);
        set(2, documentId);
        set(3, fileName);
        set(4, filePath);
        set(5, fileSize);
        set(6, httpPath);
        set(7, fileExt);
        set(8, createTime);
        set(9, createAt);
    }
}
