/**
 * This class is generated by jOOQ
 */
package com.example.mindoc_transfer.db.pojo.tables.records;


import com.example.mindoc_transfer.db.pojo.tables.MdBooks;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record19;
import org.jooq.Row19;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MdBooksRecord extends UpdatableRecordImpl<MdBooksRecord> implements Record19<Integer, String, String, Integer, String, String, Integer, String, Integer, String, Integer, String, Integer, String, String, Timestamp, Integer, Timestamp, Long> {

    private static final long serialVersionUID = 1214993545;

    /**
     * Setter for <code>mindoc_db.md_books.book_id</code>.
     */
    public void setBookId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>mindoc_db.md_books.book_id</code>.
     */
    public Integer getBookId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>mindoc_db.md_books.book_name</code>.
     */
    public void setBookName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mindoc_db.md_books.book_name</code>.
     */
    public String getBookName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mindoc_db.md_books.identify</code>.
     */
    public void setIdentify(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mindoc_db.md_books.identify</code>.
     */
    public String getIdentify() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mindoc_db.md_books.order_index</code>.
     */
    public void setOrderIndex(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>mindoc_db.md_books.order_index</code>.
     */
    public Integer getOrderIndex() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>mindoc_db.md_books.description</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>mindoc_db.md_books.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mindoc_db.md_books.label</code>.
     */
    public void setLabel(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>mindoc_db.md_books.label</code>.
     */
    public String getLabel() {
        return (String) get(5);
    }

    /**
     * Setter for <code>mindoc_db.md_books.privately_owned</code>.
     */
    public void setPrivatelyOwned(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>mindoc_db.md_books.privately_owned</code>.
     */
    public Integer getPrivatelyOwned() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>mindoc_db.md_books.private_token</code>.
     */
    public void setPrivateToken(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>mindoc_db.md_books.private_token</code>.
     */
    public String getPrivateToken() {
        return (String) get(7);
    }

    /**
     * Setter for <code>mindoc_db.md_books.status</code>.
     */
    public void setStatus(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>mindoc_db.md_books.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>mindoc_db.md_books.editor</code>.
     */
    public void setEditor(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>mindoc_db.md_books.editor</code>.
     */
    public String getEditor() {
        return (String) get(9);
    }

    /**
     * Setter for <code>mindoc_db.md_books.doc_count</code>.
     */
    public void setDocCount(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>mindoc_db.md_books.doc_count</code>.
     */
    public Integer getDocCount() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>mindoc_db.md_books.comment_status</code>.
     */
    public void setCommentStatus(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>mindoc_db.md_books.comment_status</code>.
     */
    public String getCommentStatus() {
        return (String) get(11);
    }

    /**
     * Setter for <code>mindoc_db.md_books.comment_count</code>.
     */
    public void setCommentCount(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>mindoc_db.md_books.comment_count</code>.
     */
    public Integer getCommentCount() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>mindoc_db.md_books.cover</code>.
     */
    public void setCover(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>mindoc_db.md_books.cover</code>.
     */
    public String getCover() {
        return (String) get(13);
    }

    /**
     * Setter for <code>mindoc_db.md_books.theme</code>.
     */
    public void setTheme(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>mindoc_db.md_books.theme</code>.
     */
    public String getTheme() {
        return (String) get(14);
    }

    /**
     * Setter for <code>mindoc_db.md_books.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(15, value);
    }

    /**
     * Getter for <code>mindoc_db.md_books.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(15);
    }

    /**
     * Setter for <code>mindoc_db.md_books.member_id</code>.
     */
    public void setMemberId(Integer value) {
        set(16, value);
    }

    /**
     * Getter for <code>mindoc_db.md_books.member_id</code>.
     */
    public Integer getMemberId() {
        return (Integer) get(16);
    }

    /**
     * Setter for <code>mindoc_db.md_books.modify_time</code>.
     */
    public void setModifyTime(Timestamp value) {
        set(17, value);
    }

    /**
     * Getter for <code>mindoc_db.md_books.modify_time</code>.
     */
    public Timestamp getModifyTime() {
        return (Timestamp) get(17);
    }

    /**
     * Setter for <code>mindoc_db.md_books.version</code>.
     */
    public void setVersion(Long value) {
        set(18, value);
    }

    /**
     * Getter for <code>mindoc_db.md_books.version</code>.
     */
    public Long getVersion() {
        return (Long) get(18);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record19 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row19<Integer, String, String, Integer, String, String, Integer, String, Integer, String, Integer, String, Integer, String, String, Timestamp, Integer, Timestamp, Long> fieldsRow() {
        return (Row19) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row19<Integer, String, String, Integer, String, String, Integer, String, Integer, String, Integer, String, Integer, String, String, Timestamp, Integer, Timestamp, Long> valuesRow() {
        return (Row19) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return MdBooks.MD_BOOKS.BOOK_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return MdBooks.MD_BOOKS.BOOK_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return MdBooks.MD_BOOKS.IDENTIFY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return MdBooks.MD_BOOKS.ORDER_INDEX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return MdBooks.MD_BOOKS.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return MdBooks.MD_BOOKS.LABEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return MdBooks.MD_BOOKS.PRIVATELY_OWNED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return MdBooks.MD_BOOKS.PRIVATE_TOKEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return MdBooks.MD_BOOKS.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return MdBooks.MD_BOOKS.EDITOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return MdBooks.MD_BOOKS.DOC_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return MdBooks.MD_BOOKS.COMMENT_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return MdBooks.MD_BOOKS.COMMENT_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return MdBooks.MD_BOOKS.COVER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return MdBooks.MD_BOOKS.THEME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field16() {
        return MdBooks.MD_BOOKS.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field17() {
        return MdBooks.MD_BOOKS.MEMBER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field18() {
        return MdBooks.MD_BOOKS.MODIFY_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field19() {
        return MdBooks.MD_BOOKS.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getBookId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getBookName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getIdentify();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getOrderIndex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getLabel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getPrivatelyOwned();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getPrivateToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getEditor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getDocCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getCommentStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getCommentCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getCover();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getTheme();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value16() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value17() {
        return getMemberId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value18() {
        return getModifyTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value19() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdBooksRecord value1(Integer value) {
        setBookId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdBooksRecord value2(String value) {
        setBookName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdBooksRecord value3(String value) {
        setIdentify(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdBooksRecord value4(Integer value) {
        setOrderIndex(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdBooksRecord value5(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdBooksRecord value6(String value) {
        setLabel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdBooksRecord value7(Integer value) {
        setPrivatelyOwned(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdBooksRecord value8(String value) {
        setPrivateToken(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdBooksRecord value9(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdBooksRecord value10(String value) {
        setEditor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdBooksRecord value11(Integer value) {
        setDocCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdBooksRecord value12(String value) {
        setCommentStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdBooksRecord value13(Integer value) {
        setCommentCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdBooksRecord value14(String value) {
        setCover(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdBooksRecord value15(String value) {
        setTheme(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdBooksRecord value16(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdBooksRecord value17(Integer value) {
        setMemberId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdBooksRecord value18(Timestamp value) {
        setModifyTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdBooksRecord value19(Long value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdBooksRecord values(Integer value1, String value2, String value3, Integer value4, String value5, String value6, Integer value7, String value8, Integer value9, String value10, Integer value11, String value12, Integer value13, String value14, String value15, Timestamp value16, Integer value17, Timestamp value18, Long value19) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MdBooksRecord
     */
    public MdBooksRecord() {
        super(MdBooks.MD_BOOKS);
    }

    /**
     * Create a detached, initialised MdBooksRecord
     */
    public MdBooksRecord(Integer bookId, String bookName, String identify, Integer orderIndex, String description, String label, Integer privatelyOwned, String privateToken, Integer status, String editor, Integer docCount, String commentStatus, Integer commentCount, String cover, String theme, Timestamp createTime, Integer memberId, Timestamp modifyTime, Long version) {
        super(MdBooks.MD_BOOKS);

        set(0, bookId);
        set(1, bookName);
        set(2, identify);
        set(3, orderIndex);
        set(4, description);
        set(5, label);
        set(6, privatelyOwned);
        set(7, privateToken);
        set(8, status);
        set(9, editor);
        set(10, docCount);
        set(11, commentStatus);
        set(12, commentCount);
        set(13, cover);
        set(14, theme);
        set(15, createTime);
        set(16, memberId);
        set(17, modifyTime);
        set(18, version);
    }
}
