/**
 * This class is generated by jOOQ
 */
package com.example.mindoc_transfer.db.pojo.tables.records;


import com.example.mindoc_transfer.db.pojo.tables.MdDocumentHistory;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MdDocumentHistoryRecord extends UpdatableRecordImpl<MdDocumentHistoryRecord> implements Record12<Integer, String, String, Integer, String, Integer, String, String, Integer, Timestamp, Integer, Long> {

    private static final long serialVersionUID = -2032907449;

    /**
     * Setter for <code>mindoc_db.md_document_history.history_id</code>.
     */
    public void setHistoryId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>mindoc_db.md_document_history.history_id</code>.
     */
    public Integer getHistoryId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>mindoc_db.md_document_history.action</code>.
     */
    public void setAction(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mindoc_db.md_document_history.action</code>.
     */
    public String getAction() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mindoc_db.md_document_history.action_name</code>.
     */
    public void setActionName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mindoc_db.md_document_history.action_name</code>.
     */
    public String getActionName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mindoc_db.md_document_history.document_id</code>.
     */
    public void setDocumentId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>mindoc_db.md_document_history.document_id</code>.
     */
    public Integer getDocumentId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>mindoc_db.md_document_history.document_name</code>.
     */
    public void setDocumentName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>mindoc_db.md_document_history.document_name</code>.
     */
    public String getDocumentName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mindoc_db.md_document_history.parent_id</code>.
     */
    public void setParentId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>mindoc_db.md_document_history.parent_id</code>.
     */
    public Integer getParentId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>mindoc_db.md_document_history.markdown</code>.
     */
    public void setMarkdown(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>mindoc_db.md_document_history.markdown</code>.
     */
    public String getMarkdown() {
        return (String) get(6);
    }

    /**
     * Setter for <code>mindoc_db.md_document_history.content</code>.
     */
    public void setContent(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>mindoc_db.md_document_history.content</code>.
     */
    public String getContent() {
        return (String) get(7);
    }

    /**
     * Setter for <code>mindoc_db.md_document_history.member_id</code>.
     */
    public void setMemberId(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>mindoc_db.md_document_history.member_id</code>.
     */
    public Integer getMemberId() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>mindoc_db.md_document_history.modify_time</code>.
     */
    public void setModifyTime(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>mindoc_db.md_document_history.modify_time</code>.
     */
    public Timestamp getModifyTime() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>mindoc_db.md_document_history.modify_at</code>.
     */
    public void setModifyAt(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>mindoc_db.md_document_history.modify_at</code>.
     */
    public Integer getModifyAt() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>mindoc_db.md_document_history.version</code>.
     */
    public void setVersion(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>mindoc_db.md_document_history.version</code>.
     */
    public Long getVersion() {
        return (Long) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, String, String, Integer, String, Integer, String, String, Integer, Timestamp, Integer, Long> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, String, String, Integer, String, Integer, String, String, Integer, Timestamp, Integer, Long> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return MdDocumentHistory.MD_DOCUMENT_HISTORY.HISTORY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return MdDocumentHistory.MD_DOCUMENT_HISTORY.ACTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return MdDocumentHistory.MD_DOCUMENT_HISTORY.ACTION_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return MdDocumentHistory.MD_DOCUMENT_HISTORY.DOCUMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return MdDocumentHistory.MD_DOCUMENT_HISTORY.DOCUMENT_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return MdDocumentHistory.MD_DOCUMENT_HISTORY.PARENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return MdDocumentHistory.MD_DOCUMENT_HISTORY.MARKDOWN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return MdDocumentHistory.MD_DOCUMENT_HISTORY.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return MdDocumentHistory.MD_DOCUMENT_HISTORY.MEMBER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return MdDocumentHistory.MD_DOCUMENT_HISTORY.MODIFY_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return MdDocumentHistory.MD_DOCUMENT_HISTORY.MODIFY_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field12() {
        return MdDocumentHistory.MD_DOCUMENT_HISTORY.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getHistoryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getActionName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getDocumentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDocumentName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getMarkdown();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getMemberId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getModifyTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getModifyAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value12() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdDocumentHistoryRecord value1(Integer value) {
        setHistoryId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdDocumentHistoryRecord value2(String value) {
        setAction(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdDocumentHistoryRecord value3(String value) {
        setActionName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdDocumentHistoryRecord value4(Integer value) {
        setDocumentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdDocumentHistoryRecord value5(String value) {
        setDocumentName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdDocumentHistoryRecord value6(Integer value) {
        setParentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdDocumentHistoryRecord value7(String value) {
        setMarkdown(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdDocumentHistoryRecord value8(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdDocumentHistoryRecord value9(Integer value) {
        setMemberId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdDocumentHistoryRecord value10(Timestamp value) {
        setModifyTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdDocumentHistoryRecord value11(Integer value) {
        setModifyAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdDocumentHistoryRecord value12(Long value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdDocumentHistoryRecord values(Integer value1, String value2, String value3, Integer value4, String value5, Integer value6, String value7, String value8, Integer value9, Timestamp value10, Integer value11, Long value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    @Override
    public Integer component1() {
        return null;
    }

    @Override
    public String component2() {
        return null;
    }

    @Override
    public String component3() {
        return null;
    }

    @Override
    public Integer component4() {
        return null;
    }

    @Override
    public String component5() {
        return null;
    }

    @Override
    public Integer component6() {
        return null;
    }

    @Override
    public String component7() {
        return null;
    }

    @Override
    public String component8() {
        return null;
    }

    @Override
    public Integer component9() {
        return null;
    }

    @Override
    public Timestamp component10() {
        return null;
    }

    @Override
    public Integer component11() {
        return null;
    }

    @Override
    public Long component12() {
        return null;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MdDocumentHistoryRecord
     */
    public MdDocumentHistoryRecord() {
        super(MdDocumentHistory.MD_DOCUMENT_HISTORY);
    }

    /**
     * Create a detached, initialised MdDocumentHistoryRecord
     */
    public MdDocumentHistoryRecord(Integer historyId, String action, String actionName, Integer documentId, String documentName, Integer parentId, String markdown, String content, Integer memberId, Timestamp modifyTime, Integer modifyAt, Long version) {
        super(MdDocumentHistory.MD_DOCUMENT_HISTORY);

        set(0, historyId);
        set(1, action);
        set(2, actionName);
        set(3, documentId);
        set(4, documentName);
        set(5, parentId);
        set(6, markdown);
        set(7, content);
        set(8, memberId);
        set(9, modifyTime);
        set(10, modifyAt);
        set(11, version);
    }
}
