/**
 * This class is generated by jOOQ
 */
package com.example.mindoc_transfer.db.pojo.tables.records;


import com.example.mindoc_transfer.db.pojo.tables.MdLabel;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MdLabelRecord extends UpdatableRecordImpl<MdLabelRecord> implements Record3<Integer, String, Integer> {

    private static final long serialVersionUID = -1806798107;

    /**
     * Setter for <code>mindoc_db.md_label.label_id</code>.
     */
    public void setLabelId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>mindoc_db.md_label.label_id</code>.
     */
    public Integer getLabelId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>mindoc_db.md_label.label_name</code>.
     */
    public void setLabelName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mindoc_db.md_label.label_name</code>.
     */
    public String getLabelName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mindoc_db.md_label.book_number</code>.
     */
    public void setBookNumber(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>mindoc_db.md_label.book_number</code>.
     */
    public Integer getBookNumber() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return MdLabel.MD_LABEL.LABEL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return MdLabel.MD_LABEL.LABEL_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return MdLabel.MD_LABEL.BOOK_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getLabelId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getLabelName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getBookNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdLabelRecord value1(Integer value) {
        setLabelId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdLabelRecord value2(String value) {
        setLabelName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdLabelRecord value3(Integer value) {
        setBookNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdLabelRecord values(Integer value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MdLabelRecord
     */
    public MdLabelRecord() {
        super(MdLabel.MD_LABEL);
    }

    /**
     * Create a detached, initialised MdLabelRecord
     */
    public MdLabelRecord(Integer labelId, String labelName, Integer bookNumber) {
        super(MdLabel.MD_LABEL);

        set(0, labelId);
        set(1, labelName);
        set(2, bookNumber);
    }
}
