/**
 * This class is generated by jOOQ
 */
package com.example.mindoc_transfer.db.pojo.tables.records;


import com.example.mindoc_transfer.db.pojo.tables.MdLogs;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MdLogsRecord extends UpdatableRecordImpl<MdLogsRecord> implements Record9<Long, Integer, String, String, String, String, Timestamp, String, String> {

    private static final long serialVersionUID = 1763206335;

    /**
     * Setter for <code>mindoc_db.md_logs.log_id</code>.
     */
    public void setLogId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>mindoc_db.md_logs.log_id</code>.
     */
    public Long getLogId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>mindoc_db.md_logs.member_id</code>.
     */
    public void setMemberId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>mindoc_db.md_logs.member_id</code>.
     */
    public Integer getMemberId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>mindoc_db.md_logs.category</code>.
     */
    public void setCategory(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mindoc_db.md_logs.category</code>.
     */
    public String getCategory() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mindoc_db.md_logs.content</code>.
     */
    public void setContent(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mindoc_db.md_logs.content</code>.
     */
    public String getContent() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mindoc_db.md_logs.original_data</code>.
     */
    public void setOriginalData(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>mindoc_db.md_logs.original_data</code>.
     */
    public String getOriginalData() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mindoc_db.md_logs.present_data</code>.
     */
    public void setPresentData(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>mindoc_db.md_logs.present_data</code>.
     */
    public String getPresentData() {
        return (String) get(5);
    }

    /**
     * Setter for <code>mindoc_db.md_logs.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>mindoc_db.md_logs.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>mindoc_db.md_logs.user_agent</code>.
     */
    public void setUserAgent(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>mindoc_db.md_logs.user_agent</code>.
     */
    public String getUserAgent() {
        return (String) get(7);
    }

    /**
     * Setter for <code>mindoc_db.md_logs.ip_address</code>.
     */
    public void setIpAddress(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>mindoc_db.md_logs.ip_address</code>.
     */
    public String getIpAddress() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, Integer, String, String, String, String, Timestamp, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, Integer, String, String, String, String, Timestamp, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return MdLogs.MD_LOGS.LOG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return MdLogs.MD_LOGS.MEMBER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return MdLogs.MD_LOGS.CATEGORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return MdLogs.MD_LOGS.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return MdLogs.MD_LOGS.ORIGINAL_DATA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return MdLogs.MD_LOGS.PRESENT_DATA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return MdLogs.MD_LOGS.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return MdLogs.MD_LOGS.USER_AGENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return MdLogs.MD_LOGS.IP_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getLogId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getMemberId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getOriginalData();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getPresentData();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getUserAgent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getIpAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdLogsRecord value1(Long value) {
        setLogId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdLogsRecord value2(Integer value) {
        setMemberId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdLogsRecord value3(String value) {
        setCategory(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdLogsRecord value4(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdLogsRecord value5(String value) {
        setOriginalData(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdLogsRecord value6(String value) {
        setPresentData(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdLogsRecord value7(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdLogsRecord value8(String value) {
        setUserAgent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdLogsRecord value9(String value) {
        setIpAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdLogsRecord values(Long value1, Integer value2, String value3, String value4, String value5, String value6, Timestamp value7, String value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MdLogsRecord
     */
    public MdLogsRecord() {
        super(MdLogs.MD_LOGS);
    }

    /**
     * Create a detached, initialised MdLogsRecord
     */
    public MdLogsRecord(Long logId, Integer memberId, String category, String content, String originalData, String presentData, Timestamp createTime, String userAgent, String ipAddress) {
        super(MdLogs.MD_LOGS);

        set(0, logId);
        set(1, memberId);
        set(2, category);
        set(3, content);
        set(4, originalData);
        set(5, presentData);
        set(6, createTime);
        set(7, userAgent);
        set(8, ipAddress);
    }
}
