/**
 * This class is generated by jOOQ
 */
package com.example.mindoc_transfer.db.pojo.tables.records;


import com.example.mindoc_transfer.db.pojo.tables.MdMembers;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MdMembersRecord extends UpdatableRecordImpl<MdMembersRecord> implements Record13<Integer, String, String, String, String, String, String, String, Integer, Integer, Timestamp, Integer, Timestamp> {

    private static final long serialVersionUID = -655593886;

    /**
     * Setter for <code>mindoc_db.md_members.member_id</code>.
     */
    public void setMemberId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>mindoc_db.md_members.member_id</code>.
     */
    public Integer getMemberId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>mindoc_db.md_members.account</code>.
     */
    public void setAccount(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mindoc_db.md_members.account</code>.
     */
    public String getAccount() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mindoc_db.md_members.password</code>.
     */
    public void setPassword(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mindoc_db.md_members.password</code>.
     */
    public String getPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mindoc_db.md_members.auth_method</code>.
     */
    public void setAuthMethod(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mindoc_db.md_members.auth_method</code>.
     */
    public String getAuthMethod() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mindoc_db.md_members.description</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>mindoc_db.md_members.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mindoc_db.md_members.email</code>.
     */
    public void setEmail(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>mindoc_db.md_members.email</code>.
     */
    public String getEmail() {
        return (String) get(5);
    }

    /**
     * Setter for <code>mindoc_db.md_members.phone</code>.
     */
    public void setPhone(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>mindoc_db.md_members.phone</code>.
     */
    public String getPhone() {
        return (String) get(6);
    }

    /**
     * Setter for <code>mindoc_db.md_members.avatar</code>.
     */
    public void setAvatar(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>mindoc_db.md_members.avatar</code>.
     */
    public String getAvatar() {
        return (String) get(7);
    }

    /**
     * Setter for <code>mindoc_db.md_members.role</code>.
     */
    public void setRole(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>mindoc_db.md_members.role</code>.
     */
    public Integer getRole() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>mindoc_db.md_members.status</code>.
     */
    public void setStatus(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>mindoc_db.md_members.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>mindoc_db.md_members.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>mindoc_db.md_members.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>mindoc_db.md_members.create_at</code>.
     */
    public void setCreateAt(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>mindoc_db.md_members.create_at</code>.
     */
    public Integer getCreateAt() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>mindoc_db.md_members.last_login_time</code>.
     */
    public void setLastLoginTime(Timestamp value) {
        set(12, value);
    }

    /**
     * Getter for <code>mindoc_db.md_members.last_login_time</code>.
     */
    public Timestamp getLastLoginTime() {
        return (Timestamp) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, String, String, String, String, String, String, String, Integer, Integer, Timestamp, Integer, Timestamp> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, String, String, String, String, String, String, String, Integer, Integer, Timestamp, Integer, Timestamp> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return MdMembers.MD_MEMBERS.MEMBER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return MdMembers.MD_MEMBERS.ACCOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return MdMembers.MD_MEMBERS.PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return MdMembers.MD_MEMBERS.AUTH_METHOD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return MdMembers.MD_MEMBERS.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return MdMembers.MD_MEMBERS.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return MdMembers.MD_MEMBERS.PHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return MdMembers.MD_MEMBERS.AVATAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return MdMembers.MD_MEMBERS.ROLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return MdMembers.MD_MEMBERS.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return MdMembers.MD_MEMBERS.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field12() {
        return MdMembers.MD_MEMBERS.CREATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field13() {
        return MdMembers.MD_MEMBERS.LAST_LOGIN_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getMemberId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAccount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getAuthMethod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getAvatar();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getRole();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value12() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value13() {
        return getLastLoginTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdMembersRecord value1(Integer value) {
        setMemberId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdMembersRecord value2(String value) {
        setAccount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdMembersRecord value3(String value) {
        setPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdMembersRecord value4(String value) {
        setAuthMethod(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdMembersRecord value5(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdMembersRecord value6(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdMembersRecord value7(String value) {
        setPhone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdMembersRecord value8(String value) {
        setAvatar(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdMembersRecord value9(Integer value) {
        setRole(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdMembersRecord value10(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdMembersRecord value11(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdMembersRecord value12(Integer value) {
        setCreateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdMembersRecord value13(Timestamp value) {
        setLastLoginTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdMembersRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, Integer value9, Integer value10, Timestamp value11, Integer value12, Timestamp value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    @Override
    public Integer component1() {
        return null;
    }

    @Override
    public String component2() {
        return null;
    }

    @Override
    public String component3() {
        return null;
    }

    @Override
    public String component4() {
        return null;
    }

    @Override
    public String component5() {
        return null;
    }

    @Override
    public String component6() {
        return null;
    }

    @Override
    public String component7() {
        return null;
    }

    @Override
    public String component8() {
        return null;
    }

    @Override
    public Integer component9() {
        return null;
    }

    @Override
    public Integer component10() {
        return null;
    }

    @Override
    public Timestamp component11() {
        return null;
    }

    @Override
    public Integer component12() {
        return null;
    }

    @Override
    public Timestamp component13() {
        return null;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MdMembersRecord
     */
    public MdMembersRecord() {
        super(MdMembers.MD_MEMBERS);
    }

    /**
     * Create a detached, initialised MdMembersRecord
     */
    public MdMembersRecord(Integer memberId, String account, String password, String authMethod, String description, String email, String phone, String avatar, Integer role, Integer status, Timestamp createTime, Integer createAt, Timestamp lastLoginTime) {
        super(MdMembers.MD_MEMBERS);

        set(0, memberId);
        set(1, account);
        set(2, password);
        set(3, authMethod);
        set(4, description);
        set(5, email);
        set(6, phone);
        set(7, avatar);
        set(8, role);
        set(9, status);
        set(10, createTime);
        set(11, createAt);
        set(12, lastLoginTime);
    }
}
