/**
 * This class is generated by jOOQ
 */
package com.example.mindoc_transfer.db.pojo.tables.records;


import com.example.mindoc_transfer.db.pojo.tables.MdMigrations;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MdMigrationsRecord extends UpdatableRecordImpl<MdMigrationsRecord> implements Record6<Integer, String, String, String, Timestamp, Long> {

    private static final long serialVersionUID = 46431047;

    /**
     * Setter for <code>mindoc_db.md_migrations.migration_id</code>.
     */
    public void setMigrationId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>mindoc_db.md_migrations.migration_id</code>.
     */
    public Integer getMigrationId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>mindoc_db.md_migrations.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mindoc_db.md_migrations.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mindoc_db.md_migrations.statements</code>.
     */
    public void setStatements(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mindoc_db.md_migrations.statements</code>.
     */
    public String getStatements() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mindoc_db.md_migrations.status</code>.
     */
    public void setStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mindoc_db.md_migrations.status</code>.
     */
    public String getStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mindoc_db.md_migrations.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>mindoc_db.md_migrations.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>mindoc_db.md_migrations.version</code>.
     */
    public void setVersion(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>mindoc_db.md_migrations.version</code>.
     */
    public Long getVersion() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, String, Timestamp, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, String, Timestamp, Long> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return MdMigrations.MD_MIGRATIONS.MIGRATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return MdMigrations.MD_MIGRATIONS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return MdMigrations.MD_MIGRATIONS.STATEMENTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return MdMigrations.MD_MIGRATIONS.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return MdMigrations.MD_MIGRATIONS.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return MdMigrations.MD_MIGRATIONS.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getMigrationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getStatements();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdMigrationsRecord value1(Integer value) {
        setMigrationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdMigrationsRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdMigrationsRecord value3(String value) {
        setStatements(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdMigrationsRecord value4(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdMigrationsRecord value5(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdMigrationsRecord value6(Long value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdMigrationsRecord values(Integer value1, String value2, String value3, String value4, Timestamp value5, Long value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    @Override
    public Integer component1() {
        return null;
    }

    @Override
    public String component2() {
        return null;
    }

    @Override
    public String component3() {
        return null;
    }

    @Override
    public String component4() {
        return null;
    }

    @Override
    public Timestamp component5() {
        return null;
    }

    @Override
    public Long component6() {
        return null;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MdMigrationsRecord
     */
    public MdMigrationsRecord() {
        super(MdMigrations.MD_MIGRATIONS);
    }

    /**
     * Create a detached, initialised MdMigrationsRecord
     */
    public MdMigrationsRecord(Integer migrationId, String name, String statements, String status, Timestamp createTime, Long version) {
        super(MdMigrations.MD_MIGRATIONS);

        set(0, migrationId);
        set(1, name);
        set(2, statements);
        set(3, status);
        set(4, createTime);
        set(5, version);
    }
}
