/**
 * This class is generated by jOOQ
 */
package com.example.mindoc_transfer.db.pojo.tables.records;


import com.example.mindoc_transfer.db.pojo.tables.MdOptions;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MdOptionsRecord extends UpdatableRecordImpl<MdOptionsRecord> implements Record5<Integer, String, String, String, String> {

    private static final long serialVersionUID = 41324375;

    /**
     * Setter for <code>mindoc_db.md_options.option_id</code>.
     */
    public void setOptionId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>mindoc_db.md_options.option_id</code>.
     */
    public Integer getOptionId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>mindoc_db.md_options.option_title</code>.
     */
    public void setOptionTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mindoc_db.md_options.option_title</code>.
     */
    public String getOptionTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mindoc_db.md_options.option_name</code>.
     */
    public void setOptionName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mindoc_db.md_options.option_name</code>.
     */
    public String getOptionName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mindoc_db.md_options.option_value</code>.
     */
    public void setOptionValue(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mindoc_db.md_options.option_value</code>.
     */
    public String getOptionValue() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mindoc_db.md_options.remark</code>.
     */
    public void setRemark(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>mindoc_db.md_options.remark</code>.
     */
    public String getRemark() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return MdOptions.MD_OPTIONS.OPTION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return MdOptions.MD_OPTIONS.OPTION_TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return MdOptions.MD_OPTIONS.OPTION_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return MdOptions.MD_OPTIONS.OPTION_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return MdOptions.MD_OPTIONS.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getOptionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getOptionTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getOptionName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getOptionValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdOptionsRecord value1(Integer value) {
        setOptionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdOptionsRecord value2(String value) {
        setOptionTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdOptionsRecord value3(String value) {
        setOptionName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdOptionsRecord value4(String value) {
        setOptionValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdOptionsRecord value5(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdOptionsRecord values(Integer value1, String value2, String value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    @Override
    public Integer component1() {
        return null;
    }

    @Override
    public String component2() {
        return null;
    }

    @Override
    public String component3() {
        return null;
    }

    @Override
    public String component4() {
        return null;
    }

    @Override
    public String component5() {
        return null;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MdOptionsRecord
     */
    public MdOptionsRecord() {
        super(MdOptions.MD_OPTIONS);
    }

    /**
     * Create a detached, initialised MdOptionsRecord
     */
    public MdOptionsRecord(Integer optionId, String optionTitle, String optionName, String optionValue, String remark) {
        super(MdOptions.MD_OPTIONS);

        set(0, optionId);
        set(1, optionTitle);
        set(2, optionName);
        set(3, optionValue);
        set(4, remark);
    }
}
