/**
 * This class is generated by jOOQ
 */
package com.example.mindoc_transfer.db.pojo.tables.records;


import com.example.mindoc_transfer.db.pojo.tables.OpcHelpCenterFilesStructures;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record18;
import org.jooq.Row18;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 帮助中心：文档数据表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OpcHelpCenterFilesStructuresRecord extends UpdatableRecordImpl<OpcHelpCenterFilesStructuresRecord> implements Record18<Long, Long, Long, Integer, String, String, Integer, Byte, String, String, Byte, String, Integer, Byte, Timestamp, Long, Timestamp, Long> {

    private static final long serialVersionUID = -1159630903;

    /**
     * Setter for <code>mindoc_db.opc_help_center_files_structures.id</code>. id of the record
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>mindoc_db.opc_help_center_files_structures.id</code>. id of the record
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>mindoc_db.opc_help_center_files_structures.folder_structure_id</code>. 目录结构叶子节点id，id of the eh_help_center_folders_structures
     */
    public void setFolderStructureId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>mindoc_db.opc_help_center_files_structures.folder_structure_id</code>. 目录结构叶子节点id，id of the eh_help_center_folders_structures
     */
    public Long getFolderStructureId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>mindoc_db.opc_help_center_files_structures.parent_id</code>. 上层目录id
     */
    public void setParentId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>mindoc_db.opc_help_center_files_structures.parent_id</code>. 上层目录id
     */
    public Long getParentId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>mindoc_db.opc_help_center_files_structures.level</code>. 目录节点所在层级深度
     */
    public void setLevel(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>mindoc_db.opc_help_center_files_structures.level</code>. 目录节点所在层级深度
     */
    public Integer getLevel() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>mindoc_db.opc_help_center_files_structures.path</code>. 目录路径，最大深度不限制
     */
    public void setPath(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>mindoc_db.opc_help_center_files_structures.path</code>. 目录路径，最大深度不限制
     */
    public String getPath() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mindoc_db.opc_help_center_files_structures.file_name</code>. 文档标题
     */
    public void setFileName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>mindoc_db.opc_help_center_files_structures.file_name</code>. 文档标题
     */
    public String getFileName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>mindoc_db.opc_help_center_files_structures.sort_num</code>. 排列序号
     */
    public void setSortNum(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>mindoc_db.opc_help_center_files_structures.sort_num</code>. 排列序号
     */
    public Integer getSortNum() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>mindoc_db.opc_help_center_files_structures.publish_type</code>. 文档发布状态，0-未发布，1-已发布
     */
    public void setPublishType(Byte value) {
        set(7, value);
    }

    /**
     * Getter for <code>mindoc_db.opc_help_center_files_structures.publish_type</code>. 文档发布状态，0-未发布，1-已发布
     */
    public Byte getPublishType() {
        return (Byte) get(7);
    }

    /**
     * Setter for <code>mindoc_db.opc_help_center_files_structures.publish_version_identify</code>. 文档发布版本标识，无输入限制
     */
    public void setPublishVersionIdentify(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>mindoc_db.opc_help_center_files_structures.publish_version_identify</code>. 文档发布版本标识，无输入限制
     */
    public String getPublishVersionIdentify() {
        return (String) get(8);
    }

    /**
     * Setter for <code>mindoc_db.opc_help_center_files_structures.publish_version_number</code>. 文档发布版本编号，系统根据发布时间自动生成,格式：日期时分秒
     */
    public void setPublishVersionNumber(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>mindoc_db.opc_help_center_files_structures.publish_version_number</code>. 文档发布版本编号，系统根据发布时间自动生成,格式：日期时分秒
     */
    public String getPublishVersionNumber() {
        return (String) get(9);
    }

    /**
     * Setter for <code>mindoc_db.opc_help_center_files_structures.draft_flag</code>. 文档草稿标志，0-非草稿，1-草稿
     */
    public void setDraftFlag(Byte value) {
        set(10, value);
    }

    /**
     * Getter for <code>mindoc_db.opc_help_center_files_structures.draft_flag</code>. 文档草稿标志，0-非草稿，1-草稿
     */
    public Byte getDraftFlag() {
        return (Byte) get(10);
    }

    /**
     * Setter for <code>mindoc_db.opc_help_center_files_structures.last_commit</code>. 仓库提交commit-id
     */
    public void setLastCommit(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>mindoc_db.opc_help_center_files_structures.last_commit</code>. 仓库提交commit-id
     */
    public String getLastCommit() {
        return (String) get(11);
    }

    /**
     * Setter for <code>mindoc_db.opc_help_center_files_structures.namespace_id</code>.
     */
    public void setNamespaceId(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>mindoc_db.opc_help_center_files_structures.namespace_id</code>.
     */
    public Integer getNamespaceId() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>mindoc_db.opc_help_center_files_structures.status</code>. 状态，0-无效，1-正常
     */
    public void setStatus(Byte value) {
        set(13, value);
    }

    /**
     * Getter for <code>mindoc_db.opc_help_center_files_structures.status</code>. 状态，0-无效，1-正常
     */
    public Byte getStatus() {
        return (Byte) get(13);
    }

    /**
     * Setter for <code>mindoc_db.opc_help_center_files_structures.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(14, value);
    }

    /**
     * Getter for <code>mindoc_db.opc_help_center_files_structures.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(14);
    }

    /**
     * Setter for <code>mindoc_db.opc_help_center_files_structures.creator_uid</code>.
     */
    public void setCreatorUid(Long value) {
        set(15, value);
    }

    /**
     * Getter for <code>mindoc_db.opc_help_center_files_structures.creator_uid</code>.
     */
    public Long getCreatorUid() {
        return (Long) get(15);
    }

    /**
     * Setter for <code>mindoc_db.opc_help_center_files_structures.update_time</code>.
     */
    public void setUpdateTime(Timestamp value) {
        set(16, value);
    }

    /**
     * Getter for <code>mindoc_db.opc_help_center_files_structures.update_time</code>.
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(16);
    }

    /**
     * Setter for <code>mindoc_db.opc_help_center_files_structures.updator_uid</code>.
     */
    public void setUpdatorUid(Long value) {
        set(17, value);
    }

    /**
     * Getter for <code>mindoc_db.opc_help_center_files_structures.updator_uid</code>.
     */
    public Long getUpdatorUid() {
        return (Long) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record18 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<Long, Long, Long, Integer, String, String, Integer, Byte, String, String, Byte, String, Integer, Byte, Timestamp, Long, Timestamp, Long> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<Long, Long, Long, Integer, String, String, Integer, Byte, String, String, Byte, String, Integer, Byte, Timestamp, Long, Timestamp, Long> valuesRow() {
        return (Row18) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return OpcHelpCenterFilesStructures.OPC_HELP_CENTER_FILES_STRUCTURES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return OpcHelpCenterFilesStructures.OPC_HELP_CENTER_FILES_STRUCTURES.FOLDER_STRUCTURE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return OpcHelpCenterFilesStructures.OPC_HELP_CENTER_FILES_STRUCTURES.PARENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return OpcHelpCenterFilesStructures.OPC_HELP_CENTER_FILES_STRUCTURES.LEVEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return OpcHelpCenterFilesStructures.OPC_HELP_CENTER_FILES_STRUCTURES.PATH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return OpcHelpCenterFilesStructures.OPC_HELP_CENTER_FILES_STRUCTURES.FILE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return OpcHelpCenterFilesStructures.OPC_HELP_CENTER_FILES_STRUCTURES.SORT_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field8() {
        return OpcHelpCenterFilesStructures.OPC_HELP_CENTER_FILES_STRUCTURES.PUBLISH_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return OpcHelpCenterFilesStructures.OPC_HELP_CENTER_FILES_STRUCTURES.PUBLISH_VERSION_IDENTIFY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return OpcHelpCenterFilesStructures.OPC_HELP_CENTER_FILES_STRUCTURES.PUBLISH_VERSION_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field11() {
        return OpcHelpCenterFilesStructures.OPC_HELP_CENTER_FILES_STRUCTURES.DRAFT_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return OpcHelpCenterFilesStructures.OPC_HELP_CENTER_FILES_STRUCTURES.LAST_COMMIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return OpcHelpCenterFilesStructures.OPC_HELP_CENTER_FILES_STRUCTURES.NAMESPACE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field14() {
        return OpcHelpCenterFilesStructures.OPC_HELP_CENTER_FILES_STRUCTURES.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field15() {
        return OpcHelpCenterFilesStructures.OPC_HELP_CENTER_FILES_STRUCTURES.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field16() {
        return OpcHelpCenterFilesStructures.OPC_HELP_CENTER_FILES_STRUCTURES.CREATOR_UID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field17() {
        return OpcHelpCenterFilesStructures.OPC_HELP_CENTER_FILES_STRUCTURES.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field18() {
        return OpcHelpCenterFilesStructures.OPC_HELP_CENTER_FILES_STRUCTURES.UPDATOR_UID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getFolderStructureId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getLevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getPath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getFileName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getSortNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value8() {
        return getPublishType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getPublishVersionIdentify();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getPublishVersionNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value11() {
        return getDraftFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getLastCommit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getNamespaceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value14() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value15() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value16() {
        return getCreatorUid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value17() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value18() {
        return getUpdatorUid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpcHelpCenterFilesStructuresRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpcHelpCenterFilesStructuresRecord value2(Long value) {
        setFolderStructureId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpcHelpCenterFilesStructuresRecord value3(Long value) {
        setParentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpcHelpCenterFilesStructuresRecord value4(Integer value) {
        setLevel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpcHelpCenterFilesStructuresRecord value5(String value) {
        setPath(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpcHelpCenterFilesStructuresRecord value6(String value) {
        setFileName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpcHelpCenterFilesStructuresRecord value7(Integer value) {
        setSortNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpcHelpCenterFilesStructuresRecord value8(Byte value) {
        setPublishType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpcHelpCenterFilesStructuresRecord value9(String value) {
        setPublishVersionIdentify(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpcHelpCenterFilesStructuresRecord value10(String value) {
        setPublishVersionNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpcHelpCenterFilesStructuresRecord value11(Byte value) {
        setDraftFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpcHelpCenterFilesStructuresRecord value12(String value) {
        setLastCommit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpcHelpCenterFilesStructuresRecord value13(Integer value) {
        setNamespaceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpcHelpCenterFilesStructuresRecord value14(Byte value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpcHelpCenterFilesStructuresRecord value15(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpcHelpCenterFilesStructuresRecord value16(Long value) {
        setCreatorUid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpcHelpCenterFilesStructuresRecord value17(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpcHelpCenterFilesStructuresRecord value18(Long value) {
        setUpdatorUid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpcHelpCenterFilesStructuresRecord values(Long value1, Long value2, Long value3, Integer value4, String value5, String value6, Integer value7, Byte value8, String value9, String value10, Byte value11, String value12, Integer value13, Byte value14, Timestamp value15, Long value16, Timestamp value17, Long value18) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OpcHelpCenterFilesStructuresRecord
     */
    public OpcHelpCenterFilesStructuresRecord() {
        super(OpcHelpCenterFilesStructures.OPC_HELP_CENTER_FILES_STRUCTURES);
    }

    /**
     * Create a detached, initialised OpcHelpCenterFilesStructuresRecord
     */
    public OpcHelpCenterFilesStructuresRecord(Long id, Long folderStructureId, Long parentId, Integer level, String path, String fileName, Integer sortNum, Byte publishType, String publishVersionIdentify, String publishVersionNumber, Byte draftFlag, String lastCommit, Integer namespaceId, Byte status, Timestamp createTime, Long creatorUid, Timestamp updateTime, Long updatorUid) {
        super(OpcHelpCenterFilesStructures.OPC_HELP_CENTER_FILES_STRUCTURES);

        set(0, id);
        set(1, folderStructureId);
        set(2, parentId);
        set(3, level);
        set(4, path);
        set(5, fileName);
        set(6, sortNum);
        set(7, publishType);
        set(8, publishVersionIdentify);
        set(9, publishVersionNumber);
        set(10, draftFlag);
        set(11, lastCommit);
        set(12, namespaceId);
        set(13, status);
        set(14, createTime);
        set(15, creatorUid);
        set(16, updateTime);
        set(17, updatorUid);
    }
}
