/**
 * This class is generated by jOOQ
 */
package com.example.mindoc_transfer.db.pojo.tables.records;


import com.example.mindoc_transfer.db.pojo.tables.OpcHelpCenterFoldersStructures;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * 帮助中心：帮助中心目录结构表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OpcHelpCenterFoldersStructuresRecord extends UpdatableRecordImpl<OpcHelpCenterFoldersStructuresRecord> implements Record16<Long, Long, String, Integer, String, Byte, Integer, Byte, String, Long, Integer, Byte, Timestamp, Long, Timestamp, Long> {

    private static final long serialVersionUID = 112293718;

    /**
     * Setter for <code>mindoc_db.opc_help_center_folders_structures.id</code>. id of the record
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>mindoc_db.opc_help_center_folders_structures.id</code>. id of the record
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>mindoc_db.opc_help_center_folders_structures.parent_id</code>. 上层目录id
     */
    public void setParentId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>mindoc_db.opc_help_center_folders_structures.parent_id</code>. 上层目录id
     */
    public Long getParentId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>mindoc_db.opc_help_center_folders_structures.file_name</code>. 文件或目录名称
     */
    public void setFileName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mindoc_db.opc_help_center_folders_structures.file_name</code>. 文件或目录名称
     */
    public String getFileName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mindoc_db.opc_help_center_folders_structures.level</code>. 目录节点所在层级深度
     */
    public void setLevel(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>mindoc_db.opc_help_center_folders_structures.level</code>. 目录节点所在层级深度
     */
    public Integer getLevel() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>mindoc_db.opc_help_center_folders_structures.path</code>. 目录路径，最大深度不限制
     */
    public void setPath(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>mindoc_db.opc_help_center_folders_structures.path</code>. 目录路径，最大深度不限制
     */
    public String getPath() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mindoc_db.opc_help_center_folders_structures.file_type</code>. 1：DIRECTORY-文件夹节点,2：FILE-文件节点
     */
    public void setFileType(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>mindoc_db.opc_help_center_folders_structures.file_type</code>. 1：DIRECTORY-文件夹节点,2：FILE-文件节点
     */
    public Byte getFileType() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>mindoc_db.opc_help_center_folders_structures.sort_num</code>. 排序id
     */
    public void setSortNum(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>mindoc_db.opc_help_center_folders_structures.sort_num</code>. 排序id
     */
    public Integer getSortNum() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>mindoc_db.opc_help_center_folders_structures.fixed_flag</code>. 固定分类标志，0-非固定分类：开放重命名和删除操作，1-固定分类：禁用重命名和删除操作
     */
    public void setFixedFlag(Byte value) {
        set(7, value);
    }

    /**
     * Getter for <code>mindoc_db.opc_help_center_folders_structures.fixed_flag</code>. 固定分类标志，0-非固定分类：开放重命名和删除操作，1-固定分类：禁用重命名和删除操作
     */
    public Byte getFixedFlag() {
        return (Byte) get(7);
    }

    /**
     * Setter for <code>mindoc_db.opc_help_center_folders_structures.identify</code>. 文档标识，file_type=2的节点属性
     */
    public void setIdentify(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>mindoc_db.opc_help_center_folders_structures.identify</code>. 文档标识，file_type=2的节点属性
     */
    public String getIdentify() {
        return (String) get(8);
    }

    /**
     * Setter for <code>mindoc_db.opc_help_center_folders_structures.category_id</code>. 文档分类, id of the eh_help_center_document_categories，file_type=2的节点属性
     */
    public void setCategoryId(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>mindoc_db.opc_help_center_folders_structures.category_id</code>. 文档分类, id of the eh_help_center_document_categories，file_type=2的节点属性
     */
    public Long getCategoryId() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>mindoc_db.opc_help_center_folders_structures.namespace_id</code>.
     */
    public void setNamespaceId(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>mindoc_db.opc_help_center_folders_structures.namespace_id</code>.
     */
    public Integer getNamespaceId() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>mindoc_db.opc_help_center_folders_structures.status</code>. 状态，0-无效，1-正常
     */
    public void setStatus(Byte value) {
        set(11, value);
    }

    /**
     * Getter for <code>mindoc_db.opc_help_center_folders_structures.status</code>. 状态，0-无效，1-正常
     */
    public Byte getStatus() {
        return (Byte) get(11);
    }

    /**
     * Setter for <code>mindoc_db.opc_help_center_folders_structures.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(12, value);
    }

    /**
     * Getter for <code>mindoc_db.opc_help_center_folders_structures.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(12);
    }

    /**
     * Setter for <code>mindoc_db.opc_help_center_folders_structures.creator_uid</code>.
     */
    public void setCreatorUid(Long value) {
        set(13, value);
    }

    /**
     * Getter for <code>mindoc_db.opc_help_center_folders_structures.creator_uid</code>.
     */
    public Long getCreatorUid() {
        return (Long) get(13);
    }

    /**
     * Setter for <code>mindoc_db.opc_help_center_folders_structures.update_time</code>.
     */
    public void setUpdateTime(Timestamp value) {
        set(14, value);
    }

    /**
     * Getter for <code>mindoc_db.opc_help_center_folders_structures.update_time</code>.
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(14);
    }

    /**
     * Setter for <code>mindoc_db.opc_help_center_folders_structures.updator_uid</code>.
     */
    public void setUpdatorUid(Long value) {
        set(15, value);
    }

    /**
     * Getter for <code>mindoc_db.opc_help_center_folders_structures.updator_uid</code>.
     */
    public Long getUpdatorUid() {
        return (Long) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Long, Long, String, Integer, String, Byte, Integer, Byte, String, Long, Integer, Byte, Timestamp, Long, Timestamp, Long> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Long, Long, String, Integer, String, Byte, Integer, Byte, String, Long, Integer, Byte, Timestamp, Long, Timestamp, Long> valuesRow() {
        return (Row16) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return OpcHelpCenterFoldersStructures.OPC_HELP_CENTER_FOLDERS_STRUCTURES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return OpcHelpCenterFoldersStructures.OPC_HELP_CENTER_FOLDERS_STRUCTURES.PARENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return OpcHelpCenterFoldersStructures.OPC_HELP_CENTER_FOLDERS_STRUCTURES.FILE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return OpcHelpCenterFoldersStructures.OPC_HELP_CENTER_FOLDERS_STRUCTURES.LEVEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return OpcHelpCenterFoldersStructures.OPC_HELP_CENTER_FOLDERS_STRUCTURES.PATH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field6() {
        return OpcHelpCenterFoldersStructures.OPC_HELP_CENTER_FOLDERS_STRUCTURES.FILE_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return OpcHelpCenterFoldersStructures.OPC_HELP_CENTER_FOLDERS_STRUCTURES.SORT_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field8() {
        return OpcHelpCenterFoldersStructures.OPC_HELP_CENTER_FOLDERS_STRUCTURES.FIXED_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return OpcHelpCenterFoldersStructures.OPC_HELP_CENTER_FOLDERS_STRUCTURES.IDENTIFY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field10() {
        return OpcHelpCenterFoldersStructures.OPC_HELP_CENTER_FOLDERS_STRUCTURES.CATEGORY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return OpcHelpCenterFoldersStructures.OPC_HELP_CENTER_FOLDERS_STRUCTURES.NAMESPACE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field12() {
        return OpcHelpCenterFoldersStructures.OPC_HELP_CENTER_FOLDERS_STRUCTURES.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field13() {
        return OpcHelpCenterFoldersStructures.OPC_HELP_CENTER_FOLDERS_STRUCTURES.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field14() {
        return OpcHelpCenterFoldersStructures.OPC_HELP_CENTER_FOLDERS_STRUCTURES.CREATOR_UID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field15() {
        return OpcHelpCenterFoldersStructures.OPC_HELP_CENTER_FOLDERS_STRUCTURES.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field16() {
        return OpcHelpCenterFoldersStructures.OPC_HELP_CENTER_FOLDERS_STRUCTURES.UPDATOR_UID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getFileName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getLevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getPath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value6() {
        return getFileType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getSortNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value8() {
        return getFixedFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getIdentify();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value10() {
        return getCategoryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getNamespaceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value12() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value13() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value14() {
        return getCreatorUid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value15() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value16() {
        return getUpdatorUid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpcHelpCenterFoldersStructuresRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpcHelpCenterFoldersStructuresRecord value2(Long value) {
        setParentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpcHelpCenterFoldersStructuresRecord value3(String value) {
        setFileName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpcHelpCenterFoldersStructuresRecord value4(Integer value) {
        setLevel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpcHelpCenterFoldersStructuresRecord value5(String value) {
        setPath(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpcHelpCenterFoldersStructuresRecord value6(Byte value) {
        setFileType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpcHelpCenterFoldersStructuresRecord value7(Integer value) {
        setSortNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpcHelpCenterFoldersStructuresRecord value8(Byte value) {
        setFixedFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpcHelpCenterFoldersStructuresRecord value9(String value) {
        setIdentify(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpcHelpCenterFoldersStructuresRecord value10(Long value) {
        setCategoryId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpcHelpCenterFoldersStructuresRecord value11(Integer value) {
        setNamespaceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpcHelpCenterFoldersStructuresRecord value12(Byte value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpcHelpCenterFoldersStructuresRecord value13(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpcHelpCenterFoldersStructuresRecord value14(Long value) {
        setCreatorUid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpcHelpCenterFoldersStructuresRecord value15(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpcHelpCenterFoldersStructuresRecord value16(Long value) {
        setUpdatorUid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpcHelpCenterFoldersStructuresRecord values(Long value1, Long value2, String value3, Integer value4, String value5, Byte value6, Integer value7, Byte value8, String value9, Long value10, Integer value11, Byte value12, Timestamp value13, Long value14, Timestamp value15, Long value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    @Override
    public Long component1() {
        return null;
    }

    @Override
    public Long component2() {
        return null;
    }

    @Override
    public String component3() {
        return null;
    }

    @Override
    public Integer component4() {
        return null;
    }

    @Override
    public String component5() {
        return null;
    }

    @Override
    public Byte component6() {
        return null;
    }

    @Override
    public Integer component7() {
        return null;
    }

    @Override
    public Byte component8() {
        return null;
    }

    @Override
    public String component9() {
        return null;
    }

    @Override
    public Long component10() {
        return null;
    }

    @Override
    public Integer component11() {
        return null;
    }

    @Override
    public Byte component12() {
        return null;
    }

    @Override
    public Timestamp component13() {
        return null;
    }

    @Override
    public Long component14() {
        return null;
    }

    @Override
    public Timestamp component15() {
        return null;
    }

    @Override
    public Long component16() {
        return null;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OpcHelpCenterFoldersStructuresRecord
     */
    public OpcHelpCenterFoldersStructuresRecord() {
        super(OpcHelpCenterFoldersStructures.OPC_HELP_CENTER_FOLDERS_STRUCTURES);
    }

    /**
     * Create a detached, initialised OpcHelpCenterFoldersStructuresRecord
     */
    public OpcHelpCenterFoldersStructuresRecord(Long id, Long parentId, String fileName, Integer level, String path, Byte fileType, Integer sortNum, Byte fixedFlag, String identify, Long categoryId, Integer namespaceId, Byte status, Timestamp createTime, Long creatorUid, Timestamp updateTime, Long updatorUid) {
        super(OpcHelpCenterFoldersStructures.OPC_HELP_CENTER_FOLDERS_STRUCTURES);

        set(0, id);
        set(1, parentId);
        set(2, fileName);
        set(3, level);
        set(4, path);
        set(5, fileType);
        set(6, sortNum);
        set(7, fixedFlag);
        set(8, identify);
        set(9, categoryId);
        set(10, namespaceId);
        set(11, status);
        set(12, createTime);
        set(13, creatorUid);
        set(14, updateTime);
        set(15, updatorUid);
    }
}
