/**
 * This class is generated by jOOQ
 */
package com.example.mindoc_transfer.db.pojo.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MdAttachment implements Serializable {

    private static final long serialVersionUID = -406928342;

    private Integer   attachmentId;
    private Integer   bookId;
    private Integer   documentId;
    private String    fileName;
    private String    filePath;
    private Double    fileSize;
    private String    httpPath;
    private String    fileExt;
    private Timestamp createTime;
    private Integer   createAt;

    public MdAttachment() {}

    public MdAttachment(MdAttachment value) {
        this.attachmentId = value.attachmentId;
        this.bookId = value.bookId;
        this.documentId = value.documentId;
        this.fileName = value.fileName;
        this.filePath = value.filePath;
        this.fileSize = value.fileSize;
        this.httpPath = value.httpPath;
        this.fileExt = value.fileExt;
        this.createTime = value.createTime;
        this.createAt = value.createAt;
    }

    public MdAttachment(
        Integer   attachmentId,
        Integer   bookId,
        Integer   documentId,
        String    fileName,
        String    filePath,
        Double    fileSize,
        String    httpPath,
        String    fileExt,
        Timestamp createTime,
        Integer   createAt
    ) {
        this.attachmentId = attachmentId;
        this.bookId = bookId;
        this.documentId = documentId;
        this.fileName = fileName;
        this.filePath = filePath;
        this.fileSize = fileSize;
        this.httpPath = httpPath;
        this.fileExt = fileExt;
        this.createTime = createTime;
        this.createAt = createAt;
    }

    public Integer getAttachmentId() {
        return this.attachmentId;
    }

    public void setAttachmentId(Integer attachmentId) {
        this.attachmentId = attachmentId;
    }

    public Integer getBookId() {
        return this.bookId;
    }

    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    public Integer getDocumentId() {
        return this.documentId;
    }

    public void setDocumentId(Integer documentId) {
        this.documentId = documentId;
    }

    public String getFileName() {
        return this.fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getFilePath() {
        return this.filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    public Double getFileSize() {
        return this.fileSize;
    }

    public void setFileSize(Double fileSize) {
        this.fileSize = fileSize;
    }

    public String getHttpPath() {
        return this.httpPath;
    }

    public void setHttpPath(String httpPath) {
        this.httpPath = httpPath;
    }

    public String getFileExt() {
        return this.fileExt;
    }

    public void setFileExt(String fileExt) {
        this.fileExt = fileExt;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Integer getCreateAt() {
        return this.createAt;
    }

    public void setCreateAt(Integer createAt) {
        this.createAt = createAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MdAttachment (");

        sb.append(attachmentId);
        sb.append(", ").append(bookId);
        sb.append(", ").append(documentId);
        sb.append(", ").append(fileName);
        sb.append(", ").append(filePath);
        sb.append(", ").append(fileSize);
        sb.append(", ").append(httpPath);
        sb.append(", ").append(fileExt);
        sb.append(", ").append(createTime);
        sb.append(", ").append(createAt);

        sb.append(")");
        return sb.toString();
    }
}
