/**
 * This class is generated by jOOQ
 */
package com.example.mindoc_transfer.db.pojo.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MdDocumentHistory implements Serializable {

    private static final long serialVersionUID = 1102779661;

    private Integer   historyId;
    private String    action;
    private String    actionName;
    private Integer   documentId;
    private String    documentName;
    private Integer   parentId;
    private String    markdown;
    private String    content;
    private Integer   memberId;
    private Timestamp modifyTime;
    private Integer   modifyAt;
    private Long      version;

    public MdDocumentHistory() {}

    public MdDocumentHistory(MdDocumentHistory value) {
        this.historyId = value.historyId;
        this.action = value.action;
        this.actionName = value.actionName;
        this.documentId = value.documentId;
        this.documentName = value.documentName;
        this.parentId = value.parentId;
        this.markdown = value.markdown;
        this.content = value.content;
        this.memberId = value.memberId;
        this.modifyTime = value.modifyTime;
        this.modifyAt = value.modifyAt;
        this.version = value.version;
    }

    public MdDocumentHistory(
        Integer   historyId,
        String    action,
        String    actionName,
        Integer   documentId,
        String    documentName,
        Integer   parentId,
        String    markdown,
        String    content,
        Integer   memberId,
        Timestamp modifyTime,
        Integer   modifyAt,
        Long      version
    ) {
        this.historyId = historyId;
        this.action = action;
        this.actionName = actionName;
        this.documentId = documentId;
        this.documentName = documentName;
        this.parentId = parentId;
        this.markdown = markdown;
        this.content = content;
        this.memberId = memberId;
        this.modifyTime = modifyTime;
        this.modifyAt = modifyAt;
        this.version = version;
    }

    public Integer getHistoryId() {
        return this.historyId;
    }

    public void setHistoryId(Integer historyId) {
        this.historyId = historyId;
    }

    public String getAction() {
        return this.action;
    }

    public void setAction(String action) {
        this.action = action;
    }

    public String getActionName() {
        return this.actionName;
    }

    public void setActionName(String actionName) {
        this.actionName = actionName;
    }

    public Integer getDocumentId() {
        return this.documentId;
    }

    public void setDocumentId(Integer documentId) {
        this.documentId = documentId;
    }

    public String getDocumentName() {
        return this.documentName;
    }

    public void setDocumentName(String documentName) {
        this.documentName = documentName;
    }

    public Integer getParentId() {
        return this.parentId;
    }

    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    public String getMarkdown() {
        return this.markdown;
    }

    public void setMarkdown(String markdown) {
        this.markdown = markdown;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Integer getMemberId() {
        return this.memberId;
    }

    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    public Timestamp getModifyTime() {
        return this.modifyTime;
    }

    public void setModifyTime(Timestamp modifyTime) {
        this.modifyTime = modifyTime;
    }

    public Integer getModifyAt() {
        return this.modifyAt;
    }

    public void setModifyAt(Integer modifyAt) {
        this.modifyAt = modifyAt;
    }

    public Long getVersion() {
        return this.version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MdDocumentHistory (");

        sb.append(historyId);
        sb.append(", ").append(action);
        sb.append(", ").append(actionName);
        sb.append(", ").append(documentId);
        sb.append(", ").append(documentName);
        sb.append(", ").append(parentId);
        sb.append(", ").append(markdown);
        sb.append(", ").append(content);
        sb.append(", ").append(memberId);
        sb.append(", ").append(modifyTime);
        sb.append(", ").append(modifyAt);
        sb.append(", ").append(version);

        sb.append(")");
        return sb.toString();
    }
}
