/**
 * This class is generated by jOOQ
 */
package com.example.mindoc_transfer.db.pojo.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MdLabel implements Serializable {

    private static final long serialVersionUID = -1806640293;

    private Integer labelId;
    private String  labelName;
    private Integer bookNumber;

    public MdLabel() {}

    public MdLabel(MdLabel value) {
        this.labelId = value.labelId;
        this.labelName = value.labelName;
        this.bookNumber = value.bookNumber;
    }

    public MdLabel(
        Integer labelId,
        String  labelName,
        Integer bookNumber
    ) {
        this.labelId = labelId;
        this.labelName = labelName;
        this.bookNumber = bookNumber;
    }

    public Integer getLabelId() {
        return this.labelId;
    }

    public void setLabelId(Integer labelId) {
        this.labelId = labelId;
    }

    public String getLabelName() {
        return this.labelName;
    }

    public void setLabelName(String labelName) {
        this.labelName = labelName;
    }

    public Integer getBookNumber() {
        return this.bookNumber;
    }

    public void setBookNumber(Integer bookNumber) {
        this.bookNumber = bookNumber;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MdLabel (");

        sb.append(labelId);
        sb.append(", ").append(labelName);
        sb.append(", ").append(bookNumber);

        sb.append(")");
        return sb.toString();
    }
}
