/**
 * This class is generated by jOOQ
 */
package com.example.mindoc_transfer.db.pojo.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MdMemberToken implements Serializable {

    private static final long serialVersionUID = 877191051;

    private Integer   tokenId;
    private Integer   memberId;
    private String    token;
    private String    email;
    private Byte      isValid;
    private Timestamp validTime;
    private Timestamp sendTime;

    public MdMemberToken() {}

    public MdMemberToken(MdMemberToken value) {
        this.tokenId = value.tokenId;
        this.memberId = value.memberId;
        this.token = value.token;
        this.email = value.email;
        this.isValid = value.isValid;
        this.validTime = value.validTime;
        this.sendTime = value.sendTime;
    }

    public MdMemberToken(
        Integer   tokenId,
        Integer   memberId,
        String    token,
        String    email,
        Byte      isValid,
        Timestamp validTime,
        Timestamp sendTime
    ) {
        this.tokenId = tokenId;
        this.memberId = memberId;
        this.token = token;
        this.email = email;
        this.isValid = isValid;
        this.validTime = validTime;
        this.sendTime = sendTime;
    }

    public Integer getTokenId() {
        return this.tokenId;
    }

    public void setTokenId(Integer tokenId) {
        this.tokenId = tokenId;
    }

    public Integer getMemberId() {
        return this.memberId;
    }

    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    public String getToken() {
        return this.token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Byte getIsValid() {
        return this.isValid;
    }

    public void setIsValid(Byte isValid) {
        this.isValid = isValid;
    }

    public Timestamp getValidTime() {
        return this.validTime;
    }

    public void setValidTime(Timestamp validTime) {
        this.validTime = validTime;
    }

    public Timestamp getSendTime() {
        return this.sendTime;
    }

    public void setSendTime(Timestamp sendTime) {
        this.sendTime = sendTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MdMemberToken (");

        sb.append(tokenId);
        sb.append(", ").append(memberId);
        sb.append(", ").append(token);
        sb.append(", ").append(email);
        sb.append(", ").append(isValid);
        sb.append(", ").append(validTime);
        sb.append(", ").append(sendTime);

        sb.append(")");
        return sb.toString();
    }
}
