/**
 * This class is generated by jOOQ
 */
package com.example.mindoc_transfer.db.pojo.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 帮助中心：文档数据表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OpcHelpCenterFilesStructures implements Serializable {

    private static final long serialVersionUID = -1275346387;

    private Long      id;
    private Long      folderStructureId;
    private Long      parentId;
    private Integer   level;
    private String    path;
    private String    fileName;
    private Integer   sortNum;
    private Byte      publishType;
    private String    publishVersionIdentify;
    private String    publishVersionNumber;
    private Byte      draftFlag;
    private String    lastCommit;
    private Integer   namespaceId;
    private Byte      status;
    private Timestamp createTime;
    private Long      creatorUid;
    private Timestamp updateTime;
    private Long      updatorUid;

    public OpcHelpCenterFilesStructures() {}

    public OpcHelpCenterFilesStructures(OpcHelpCenterFilesStructures value) {
        this.id = value.id;
        this.folderStructureId = value.folderStructureId;
        this.parentId = value.parentId;
        this.level = value.level;
        this.path = value.path;
        this.fileName = value.fileName;
        this.sortNum = value.sortNum;
        this.publishType = value.publishType;
        this.publishVersionIdentify = value.publishVersionIdentify;
        this.publishVersionNumber = value.publishVersionNumber;
        this.draftFlag = value.draftFlag;
        this.lastCommit = value.lastCommit;
        this.namespaceId = value.namespaceId;
        this.status = value.status;
        this.createTime = value.createTime;
        this.creatorUid = value.creatorUid;
        this.updateTime = value.updateTime;
        this.updatorUid = value.updatorUid;
    }

    public OpcHelpCenterFilesStructures(
        Long      id,
        Long      folderStructureId,
        Long      parentId,
        Integer   level,
        String    path,
        String    fileName,
        Integer   sortNum,
        Byte      publishType,
        String    publishVersionIdentify,
        String    publishVersionNumber,
        Byte      draftFlag,
        String    lastCommit,
        Integer   namespaceId,
        Byte      status,
        Timestamp createTime,
        Long      creatorUid,
        Timestamp updateTime,
        Long      updatorUid
    ) {
        this.id = id;
        this.folderStructureId = folderStructureId;
        this.parentId = parentId;
        this.level = level;
        this.path = path;
        this.fileName = fileName;
        this.sortNum = sortNum;
        this.publishType = publishType;
        this.publishVersionIdentify = publishVersionIdentify;
        this.publishVersionNumber = publishVersionNumber;
        this.draftFlag = draftFlag;
        this.lastCommit = lastCommit;
        this.namespaceId = namespaceId;
        this.status = status;
        this.createTime = createTime;
        this.creatorUid = creatorUid;
        this.updateTime = updateTime;
        this.updatorUid = updatorUid;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getFolderStructureId() {
        return this.folderStructureId;
    }

    public void setFolderStructureId(Long folderStructureId) {
        this.folderStructureId = folderStructureId;
    }

    public Long getParentId() {
        return this.parentId;
    }

    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    public Integer getLevel() {
        return this.level;
    }

    public void setLevel(Integer level) {
        this.level = level;
    }

    public String getPath() {
        return this.path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getFileName() {
        return this.fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public Integer getSortNum() {
        return this.sortNum;
    }

    public void setSortNum(Integer sortNum) {
        this.sortNum = sortNum;
    }

    public Byte getPublishType() {
        return this.publishType;
    }

    public void setPublishType(Byte publishType) {
        this.publishType = publishType;
    }

    public String getPublishVersionIdentify() {
        return this.publishVersionIdentify;
    }

    public void setPublishVersionIdentify(String publishVersionIdentify) {
        this.publishVersionIdentify = publishVersionIdentify;
    }

    public String getPublishVersionNumber() {
        return this.publishVersionNumber;
    }

    public void setPublishVersionNumber(String publishVersionNumber) {
        this.publishVersionNumber = publishVersionNumber;
    }

    public Byte getDraftFlag() {
        return this.draftFlag;
    }

    public void setDraftFlag(Byte draftFlag) {
        this.draftFlag = draftFlag;
    }

    public String getLastCommit() {
        return this.lastCommit;
    }

    public void setLastCommit(String lastCommit) {
        this.lastCommit = lastCommit;
    }

    public Integer getNamespaceId() {
        return this.namespaceId;
    }

    public void setNamespaceId(Integer namespaceId) {
        this.namespaceId = namespaceId;
    }

    public Byte getStatus() {
        return this.status;
    }

    public void setStatus(Byte status) {
        this.status = status;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Long getCreatorUid() {
        return this.creatorUid;
    }

    public void setCreatorUid(Long creatorUid) {
        this.creatorUid = creatorUid;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    public Long getUpdatorUid() {
        return this.updatorUid;
    }

    public void setUpdatorUid(Long updatorUid) {
        this.updatorUid = updatorUid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OpcHelpCenterFilesStructures (");

        sb.append(id);
        sb.append(", ").append(folderStructureId);
        sb.append(", ").append(parentId);
        sb.append(", ").append(level);
        sb.append(", ").append(path);
        sb.append(", ").append(fileName);
        sb.append(", ").append(sortNum);
        sb.append(", ").append(publishType);
        sb.append(", ").append(publishVersionIdentify);
        sb.append(", ").append(publishVersionNumber);
        sb.append(", ").append(draftFlag);
        sb.append(", ").append(lastCommit);
        sb.append(", ").append(namespaceId);
        sb.append(", ").append(status);
        sb.append(", ").append(createTime);
        sb.append(", ").append(creatorUid);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(updatorUid);

        sb.append(")");
        return sb.toString();
    }
}
