/**
 * This class is generated by jOOQ
 */
package com.example.mindoc_transfer.db.pojo.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OpcHelpCenterAttachments implements Serializable {

    private static final long serialVersionUID = -1718402026;

    private Integer   id;
    private Long      folderStructureId;
    private Integer   fileStructureId;
    private String    fileUrl;
    private String    fileName;
    private String    filePath;
    private Double    fileSize;
    private String    httpPath;
    private String    fileExt;
    private Timestamp createTime;
    private Integer   createAt;

    public OpcHelpCenterAttachments() {}

    public OpcHelpCenterAttachments(OpcHelpCenterAttachments value) {
        this.id = value.id;
        this.folderStructureId = value.folderStructureId;
        this.fileStructureId = value.fileStructureId;
        this.fileUrl = value.fileUrl;
        this.fileName = value.fileName;
        this.filePath = value.filePath;
        this.fileSize = value.fileSize;
        this.httpPath = value.httpPath;
        this.fileExt = value.fileExt;
        this.createTime = value.createTime;
        this.createAt = value.createAt;
    }

    public OpcHelpCenterAttachments(
        Integer   id,
        Long      folderStructureId,
        Integer   fileStructureId,
        String    fileUrl,
        String    fileName,
        String    filePath,
        Double    fileSize,
        String    httpPath,
        String    fileExt,
        Timestamp createTime,
        Integer   createAt
    ) {
        this.id = id;
        this.folderStructureId = folderStructureId;
        this.fileStructureId = fileStructureId;
        this.fileUrl = fileUrl;
        this.fileName = fileName;
        this.filePath = filePath;
        this.fileSize = fileSize;
        this.httpPath = httpPath;
        this.fileExt = fileExt;
        this.createTime = createTime;
        this.createAt = createAt;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Long getFolderStructureId() {
        return this.folderStructureId;
    }

    public void setFolderStructureId(Long folderStructureId) {
        this.folderStructureId = folderStructureId;
    }

    public Integer getFileStructureId() {
        return this.fileStructureId;
    }

    public void setFileStructureId(Integer fileStructureId) {
        this.fileStructureId = fileStructureId;
    }

    public String getFileUrl() {
        return this.fileUrl;
    }

    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl;
    }

    public String getFileName() {
        return this.fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getFilePath() {
        return this.filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    public Double getFileSize() {
        return this.fileSize;
    }

    public void setFileSize(Double fileSize) {
        this.fileSize = fileSize;
    }

    public String getHttpPath() {
        return this.httpPath;
    }

    public void setHttpPath(String httpPath) {
        this.httpPath = httpPath;
    }

    public String getFileExt() {
        return this.fileExt;
    }

    public void setFileExt(String fileExt) {
        this.fileExt = fileExt;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Integer getCreateAt() {
        return this.createAt;
    }

    public void setCreateAt(Integer createAt) {
        this.createAt = createAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OpcHelpCenterAttachments (");

        sb.append(id);
        sb.append(", ").append(folderStructureId);
        sb.append(", ").append(fileStructureId);
        sb.append(", ").append(fileUrl);
        sb.append(", ").append(fileName);
        sb.append(", ").append(filePath);
        sb.append(", ").append(fileSize);
        sb.append(", ").append(httpPath);
        sb.append(", ").append(fileExt);
        sb.append(", ").append(createTime);
        sb.append(", ").append(createAt);

        sb.append(")");
        return sb.toString();
    }
}
