/**
 * This class is generated by jOOQ
 */
package com.example.mindoc_transfer.db.pojo.tables;


import com.example.mindoc_transfer.db.pojo.Keys;
import com.example.mindoc_transfer.db.pojo.MindocDb;
import com.example.mindoc_transfer.db.pojo.tables.records.MdLabelRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MdLabel extends TableImpl<MdLabelRecord> {

    private static final long serialVersionUID = -481240922;

    /**
     * The reference instance of <code>mindoc_db.md_label</code>
     */
    public static final MdLabel MD_LABEL = new MdLabel();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MdLabelRecord> getRecordType() {
        return MdLabelRecord.class;
    }

    /**
     * The column <code>mindoc_db.md_label.label_id</code>.
     */
    public final TableField<MdLabelRecord, Integer> LABEL_ID = createField("label_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>mindoc_db.md_label.label_name</code>.
     */
    public final TableField<MdLabelRecord, String> LABEL_NAME = createField("label_name", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false).defaultValue(org.jooq.impl.DSL.field("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mindoc_db.md_label.book_number</code>.
     */
    public final TableField<MdLabelRecord, Integer> BOOK_NUMBER = createField("book_number", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>mindoc_db.md_label</code> table reference
     */
    public MdLabel() {
        this("md_label", null);
    }

    /**
     * Create an aliased <code>mindoc_db.md_label</code> table reference
     */
    public MdLabel(String alias) {
        this(alias, MD_LABEL);
    }

    private MdLabel(String alias, Table<MdLabelRecord> aliased) {
        this(alias, aliased, null);
    }

    private MdLabel(String alias, Table<MdLabelRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return MindocDb.MINDOC_DB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<MdLabelRecord, Integer> getIdentity() {
        return Keys.IDENTITY_MD_LABEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<MdLabelRecord> getPrimaryKey() {
        return Keys.KEY_MD_LABEL_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<MdLabelRecord>> getKeys() {
        return Arrays.<UniqueKey<MdLabelRecord>>asList(Keys.KEY_MD_LABEL_PRIMARY, Keys.KEY_MD_LABEL_LABEL_NAME);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdLabel as(String alias) {
        return new MdLabel(alias, this);
    }

    /**
     * Rename this table
     */
    public MdLabel rename(String name) {
        return new MdLabel(name, null);
    }
}
