/**
 * This class is generated by jOOQ
 */
package com.example.mindoc_transfer.db.pojo.tables;


import com.example.mindoc_transfer.db.pojo.Keys;
import com.example.mindoc_transfer.db.pojo.MindocDb;
import com.example.mindoc_transfer.db.pojo.tables.records.MdOptionsRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MdOptions extends TableImpl<MdOptionsRecord> {

    private static final long serialVersionUID = -789256449;

    /**
     * The reference instance of <code>mindoc_db.md_options</code>
     */
    public static final MdOptions MD_OPTIONS = new MdOptions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MdOptionsRecord> getRecordType() {
        return MdOptionsRecord.class;
    }

    /**
     * The column <code>mindoc_db.md_options.option_id</code>.
     */
    public final TableField<MdOptionsRecord, Integer> OPTION_ID = createField("option_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>mindoc_db.md_options.option_title</code>.
     */
    public final TableField<MdOptionsRecord, String> OPTION_TITLE = createField("option_title", org.jooq.impl.SQLDataType.VARCHAR.length(500).nullable(false).defaultValue(org.jooq.impl.DSL.field("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mindoc_db.md_options.option_name</code>.
     */
    public final TableField<MdOptionsRecord, String> OPTION_NAME = createField("option_name", org.jooq.impl.SQLDataType.VARCHAR.length(80).nullable(false).defaultValue(org.jooq.impl.DSL.field("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mindoc_db.md_options.option_value</code>.
     */
    public final TableField<MdOptionsRecord, String> OPTION_VALUE = createField("option_value", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>mindoc_db.md_options.remark</code>.
     */
    public final TableField<MdOptionsRecord, String> REMARK = createField("remark", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>mindoc_db.md_options</code> table reference
     */
    public MdOptions() {
        this("md_options", null);
    }

    /**
     * Create an aliased <code>mindoc_db.md_options</code> table reference
     */
    public MdOptions(String alias) {
        this(alias, MD_OPTIONS);
    }

    private MdOptions(String alias, Table<MdOptionsRecord> aliased) {
        this(alias, aliased, null);
    }

    private MdOptions(String alias, Table<MdOptionsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return MindocDb.MINDOC_DB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<MdOptionsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_MD_OPTIONS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<MdOptionsRecord> getPrimaryKey() {
        return Keys.KEY_MD_OPTIONS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<MdOptionsRecord>> getKeys() {
        return Arrays.<UniqueKey<MdOptionsRecord>>asList(Keys.KEY_MD_OPTIONS_PRIMARY, Keys.KEY_MD_OPTIONS_OPTION_NAME);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdOptions as(String alias) {
        return new MdOptions(alias, this);
    }

    /**
     * Rename this table
     */
    public MdOptions rename(String name) {
        return new MdOptions(name, null);
    }
}
