/**
 * This class is generated by jOOQ
 */
package com.example.mindoc_transfer.db.pojo.tables;


import com.example.mindoc_transfer.db.pojo.Keys;
import com.example.mindoc_transfer.db.pojo.MindocDb;
import com.example.mindoc_transfer.db.pojo.tables.records.MdRelationshipRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MdRelationship extends TableImpl<MdRelationshipRecord> {

    private static final long serialVersionUID = 1035017623;

    /**
     * The reference instance of <code>mindoc_db.md_relationship</code>
     */
    public static final MdRelationship MD_RELATIONSHIP = new MdRelationship();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MdRelationshipRecord> getRecordType() {
        return MdRelationshipRecord.class;
    }

    /**
     * The column <code>mindoc_db.md_relationship.relationship_id</code>.
     */
    public final TableField<MdRelationshipRecord, Integer> RELATIONSHIP_ID = createField("relationship_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>mindoc_db.md_relationship.member_id</code>.
     */
    public final TableField<MdRelationshipRecord, Integer> MEMBER_ID = createField("member_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>mindoc_db.md_relationship.book_id</code>.
     */
    public final TableField<MdRelationshipRecord, Integer> BOOK_ID = createField("book_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>mindoc_db.md_relationship.role_id</code>.
     */
    public final TableField<MdRelationshipRecord, Integer> ROLE_ID = createField("role_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>mindoc_db.md_relationship</code> table reference
     */
    public MdRelationship() {
        this("md_relationship", null);
    }

    /**
     * Create an aliased <code>mindoc_db.md_relationship</code> table reference
     */
    public MdRelationship(String alias) {
        this(alias, MD_RELATIONSHIP);
    }

    private MdRelationship(String alias, Table<MdRelationshipRecord> aliased) {
        this(alias, aliased, null);
    }

    private MdRelationship(String alias, Table<MdRelationshipRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return MindocDb.MINDOC_DB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<MdRelationshipRecord, Integer> getIdentity() {
        return Keys.IDENTITY_MD_RELATIONSHIP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<MdRelationshipRecord> getPrimaryKey() {
        return Keys.KEY_MD_RELATIONSHIP_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<MdRelationshipRecord>> getKeys() {
        return Arrays.<UniqueKey<MdRelationshipRecord>>asList(Keys.KEY_MD_RELATIONSHIP_PRIMARY, Keys.KEY_MD_RELATIONSHIP_MEMBER_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdRelationship as(String alias) {
        return new MdRelationship(alias, this);
    }

    /**
     * Rename this table
     */
    public MdRelationship rename(String name) {
        return new MdRelationship(name, null);
    }
}
