/**
 * This class is generated by jOOQ
 */
package com.example.mindoc_transfer.db.pojo.tables;


import com.example.mindoc_transfer.db.pojo.Keys;
import com.example.mindoc_transfer.db.pojo.MindocDb;
import com.example.mindoc_transfer.db.pojo.tables.records.OpcHelpCenterAttachmentsRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OpcHelpCenterAttachments extends TableImpl<OpcHelpCenterAttachmentsRecord> {

    private static final long serialVersionUID = -2041867215;

    /**
     * The reference instance of <code>mindoc_db.opc_help_center_attachments</code>
     */
    public static final OpcHelpCenterAttachments OPC_HELP_CENTER_ATTACHMENTS = new OpcHelpCenterAttachments();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OpcHelpCenterAttachmentsRecord> getRecordType() {
        return OpcHelpCenterAttachmentsRecord.class;
    }

    /**
     * The column <code>mindoc_db.opc_help_center_attachments.id</code>. id of attachment
     */
    public final TableField<OpcHelpCenterAttachmentsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "id of attachment");

    /**
     * The column <code>mindoc_db.opc_help_center_attachments.folder_structure_id</code>. 目录结构叶子节点id，id of the opc_help_center_folders_structures
     */
    public final TableField<OpcHelpCenterAttachmentsRecord, Long> FOLDER_STRUCTURE_ID = createField("folder_structure_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "目录结构叶子节点id，id of the opc_help_center_folders_structures");

    /**
     * The column <code>mindoc_db.opc_help_center_attachments.file_structure_id</code>. 章节节点id，id of the opc_help_center_files_structures
     */
    public final TableField<OpcHelpCenterAttachmentsRecord, Integer> FILE_STRUCTURE_ID = createField("file_structure_id", org.jooq.impl.SQLDataType.INTEGER, this, "章节节点id，id of the opc_help_center_files_structures");

    /**
     * The column <code>mindoc_db.opc_help_center_attachments.file_url</code>. cententServer文本下载路径
     */
    public final TableField<OpcHelpCenterAttachmentsRecord, String> FILE_URL = createField("file_url", org.jooq.impl.SQLDataType.VARCHAR.length(2000).nullable(false).defaultValue(org.jooq.impl.DSL.field("", org.jooq.impl.SQLDataType.VARCHAR)), this, "cententServer文本下载路径");

    /**
     * The column <code>mindoc_db.opc_help_center_attachments.file_name</code>.
     */
    public final TableField<OpcHelpCenterAttachmentsRecord, String> FILE_NAME = createField("file_name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false).defaultValue(org.jooq.impl.DSL.field("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mindoc_db.opc_help_center_attachments.file_path</code>.
     */
    public final TableField<OpcHelpCenterAttachmentsRecord, String> FILE_PATH = createField("file_path", org.jooq.impl.SQLDataType.VARCHAR.length(2000).nullable(false).defaultValue(org.jooq.impl.DSL.field("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mindoc_db.opc_help_center_attachments.file_size</code>.
     */
    public final TableField<OpcHelpCenterAttachmentsRecord, Double> FILE_SIZE = createField("file_size", org.jooq.impl.SQLDataType.DOUBLE.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.DOUBLE)), this, "");

    /**
     * The column <code>mindoc_db.opc_help_center_attachments.http_path</code>.
     */
    public final TableField<OpcHelpCenterAttachmentsRecord, String> HTTP_PATH = createField("http_path", org.jooq.impl.SQLDataType.VARCHAR.length(2000).nullable(false).defaultValue(org.jooq.impl.DSL.field("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mindoc_db.opc_help_center_attachments.file_ext</code>.
     */
    public final TableField<OpcHelpCenterAttachmentsRecord, String> FILE_EXT = createField("file_ext", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false).defaultValue(org.jooq.impl.DSL.field("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mindoc_db.opc_help_center_attachments.create_time</code>.
     */
    public final TableField<OpcHelpCenterAttachmentsRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>mindoc_db.opc_help_center_attachments.create_at</code>.
     */
    public final TableField<OpcHelpCenterAttachmentsRecord, Integer> CREATE_AT = createField("create_at", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>mindoc_db.opc_help_center_attachments</code> table reference
     */
    public OpcHelpCenterAttachments() {
        this("opc_help_center_attachments", null);
    }

    /**
     * Create an aliased <code>mindoc_db.opc_help_center_attachments</code> table reference
     */
    public OpcHelpCenterAttachments(String alias) {
        this(alias, OPC_HELP_CENTER_ATTACHMENTS);
    }

    private OpcHelpCenterAttachments(String alias, Table<OpcHelpCenterAttachmentsRecord> aliased) {
        this(alias, aliased, null);
    }

    private OpcHelpCenterAttachments(String alias, Table<OpcHelpCenterAttachmentsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return MindocDb.MINDOC_DB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<OpcHelpCenterAttachmentsRecord> getPrimaryKey() {
        return Keys.KEY_OPC_HELP_CENTER_ATTACHMENTS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<OpcHelpCenterAttachmentsRecord>> getKeys() {
        return Arrays.<UniqueKey<OpcHelpCenterAttachmentsRecord>>asList(Keys.KEY_OPC_HELP_CENTER_ATTACHMENTS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpcHelpCenterAttachments as(String alias) {
        return new OpcHelpCenterAttachments(alias, this);
    }

    /**
     * Rename this table
     */
    public OpcHelpCenterAttachments rename(String name) {
        return new OpcHelpCenterAttachments(name, null);
    }
}
