/**
 * This class is generated by jOOQ
 */
package com.example.mindoc_transfer.db.pojo.tables;


import com.example.mindoc_transfer.db.pojo.Keys;
import com.example.mindoc_transfer.db.pojo.MindocDb;
import com.example.mindoc_transfer.db.pojo.tables.records.OpcHelpCenterFilesStructuresRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * 帮助中心：文档数据表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OpcHelpCenterFilesStructures extends TableImpl<OpcHelpCenterFilesStructuresRecord> {

    private static final long serialVersionUID = 2025119832;

    /**
     * The reference instance of <code>mindoc_db.opc_help_center_files_structures</code>
     */
    public static final OpcHelpCenterFilesStructures OPC_HELP_CENTER_FILES_STRUCTURES = new OpcHelpCenterFilesStructures();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OpcHelpCenterFilesStructuresRecord> getRecordType() {
        return OpcHelpCenterFilesStructuresRecord.class;
    }

    /**
     * The column <code>mindoc_db.opc_help_center_files_structures.id</code>. id of the record
     */
    public final TableField<OpcHelpCenterFilesStructuresRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "id of the record");

    /**
     * The column <code>mindoc_db.opc_help_center_files_structures.folder_structure_id</code>. 目录结构叶子节点id，id of the eh_help_center_folders_structures
     */
    public final TableField<OpcHelpCenterFilesStructuresRecord, Long> FOLDER_STRUCTURE_ID = createField("folder_structure_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "目录结构叶子节点id，id of the eh_help_center_folders_structures");

    /**
     * The column <code>mindoc_db.opc_help_center_files_structures.parent_id</code>. 上层目录id
     */
    public final TableField<OpcHelpCenterFilesStructuresRecord, Long> PARENT_ID = createField("parent_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "上层目录id");

    /**
     * The column <code>mindoc_db.opc_help_center_files_structures.level</code>. 目录节点所在层级深度
     */
    public final TableField<OpcHelpCenterFilesStructuresRecord, Integer> LEVEL = createField("level", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "目录节点所在层级深度");

    /**
     * The column <code>mindoc_db.opc_help_center_files_structures.path</code>. 目录路径，最大深度不限制
     */
    public final TableField<OpcHelpCenterFilesStructuresRecord, String> PATH = createField("path", org.jooq.impl.SQLDataType.VARCHAR.length(128).nullable(false), this, "目录路径，最大深度不限制");

    /**
     * The column <code>mindoc_db.opc_help_center_files_structures.file_name</code>. 文档标题
     */
    public final TableField<OpcHelpCenterFilesStructuresRecord, String> FILE_NAME = createField("file_name", org.jooq.impl.SQLDataType.VARCHAR.length(128).nullable(false), this, "文档标题");

    /**
     * The column <code>mindoc_db.opc_help_center_files_structures.sort_num</code>. 排列序号
     */
    public final TableField<OpcHelpCenterFilesStructuresRecord, Integer> SORT_NUM = createField("sort_num", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "排列序号");

    /**
     * The column <code>mindoc_db.opc_help_center_files_structures.publish_type</code>. 文档发布状态，0-未发布，1-已发布
     */
    public final TableField<OpcHelpCenterFilesStructuresRecord, Byte> PUBLISH_TYPE = createField("publish_type", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.TINYINT)), this, "文档发布状态，0-未发布，1-已发布");

    /**
     * The column <code>mindoc_db.opc_help_center_files_structures.publish_version_identify</code>. 文档发布版本标识，无输入限制
     */
    public final TableField<OpcHelpCenterFilesStructuresRecord, String> PUBLISH_VERSION_IDENTIFY = createField("publish_version_identify", org.jooq.impl.SQLDataType.CLOB, this, "文档发布版本标识，无输入限制");

    /**
     * The column <code>mindoc_db.opc_help_center_files_structures.publish_version_number</code>. 文档发布版本编号，系统根据发布时间自动生成,格式：日期时分秒
     */
    public final TableField<OpcHelpCenterFilesStructuresRecord, String> PUBLISH_VERSION_NUMBER = createField("publish_version_number", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "文档发布版本编号，系统根据发布时间自动生成,格式：日期时分秒");

    /**
     * The column <code>mindoc_db.opc_help_center_files_structures.draft_flag</code>. 文档草稿标志，0-非草稿，1-草稿
     */
    public final TableField<OpcHelpCenterFilesStructuresRecord, Byte> DRAFT_FLAG = createField("draft_flag", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.TINYINT)), this, "文档草稿标志，0-非草稿，1-草稿");

    /**
     * The column <code>mindoc_db.opc_help_center_files_structures.last_commit</code>. 仓库提交commit-id
     */
    public final TableField<OpcHelpCenterFilesStructuresRecord, String> LAST_COMMIT = createField("last_commit", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "仓库提交commit-id");

    /**
     * The column <code>mindoc_db.opc_help_center_files_structures.namespace_id</code>.
     */
    public final TableField<OpcHelpCenterFilesStructuresRecord, Integer> NAMESPACE_ID = createField("namespace_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>mindoc_db.opc_help_center_files_structures.status</code>. 状态，0-无效，1-正常
     */
    public final TableField<OpcHelpCenterFilesStructuresRecord, Byte> STATUS = createField("status", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.field("1", org.jooq.impl.SQLDataType.TINYINT)), this, "状态，0-无效，1-正常");

    /**
     * The column <code>mindoc_db.opc_help_center_files_structures.create_time</code>.
     */
    public final TableField<OpcHelpCenterFilesStructuresRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>mindoc_db.opc_help_center_files_structures.creator_uid</code>.
     */
    public final TableField<OpcHelpCenterFilesStructuresRecord, Long> CREATOR_UID = createField("creator_uid", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>mindoc_db.opc_help_center_files_structures.update_time</code>.
     */
    public final TableField<OpcHelpCenterFilesStructuresRecord, Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>mindoc_db.opc_help_center_files_structures.updator_uid</code>.
     */
    public final TableField<OpcHelpCenterFilesStructuresRecord, Long> UPDATOR_UID = createField("updator_uid", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>mindoc_db.opc_help_center_files_structures</code> table reference
     */
    public OpcHelpCenterFilesStructures() {
        this("opc_help_center_files_structures", null);
    }

    /**
     * Create an aliased <code>mindoc_db.opc_help_center_files_structures</code> table reference
     */
    public OpcHelpCenterFilesStructures(String alias) {
        this(alias, OPC_HELP_CENTER_FILES_STRUCTURES);
    }

    private OpcHelpCenterFilesStructures(String alias, Table<OpcHelpCenterFilesStructuresRecord> aliased) {
        this(alias, aliased, null);
    }

    private OpcHelpCenterFilesStructures(String alias, Table<OpcHelpCenterFilesStructuresRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "帮助中心：文档数据表");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return MindocDb.MINDOC_DB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<OpcHelpCenterFilesStructuresRecord> getPrimaryKey() {
        return Keys.KEY_OPC_HELP_CENTER_FILES_STRUCTURES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<OpcHelpCenterFilesStructuresRecord>> getKeys() {
        return Arrays.<UniqueKey<OpcHelpCenterFilesStructuresRecord>>asList(Keys.KEY_OPC_HELP_CENTER_FILES_STRUCTURES_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OpcHelpCenterFilesStructures as(String alias) {
        return new OpcHelpCenterFilesStructures(alias, this);
    }

    /**
     * Rename this table
     */
    public OpcHelpCenterFilesStructures rename(String name) {
        return new OpcHelpCenterFilesStructures(name, null);
    }
}
